= Best Practices

== NativeScript Best Practices

=== The story of 😢 or 😊

Over the years several distinct best practices have emerged when working with NativeScript and we'd like to outline a few here for you in hopes that you can enjoy NativeScripting as much as we do. More importantly though, that your end product gives you all the right _feels_ you expect.

We are providing a sample "vanilla" NativeScript app which shows some of the bad vs. good practices for you to run and see for yourself.
Using vanilla NativeScript is a great way to see the raw examples of why these are bad and good practices which are applicable to any frontend framework integration. Each framework integration effectively utilizes these same practices for it's own various cases.

Clone and see for yourself: https://github.com/NativeScript/examples-best-practices

* xref:view-bindings.adoc[View bindings]
* xref:listviews.adoc[ListViews]
* xref:if-things.adoc[hidden, visibility, v-if, ngIf and all those "if" things]
* xref:rogue-timers.adoc[Rogue timers and intervals]
* xref:native-class.adoc[Various usages of @NativeClass() decorator]
* xref:android-tips.adoc[Android tips]
* xref:ios-tips.adoc[iOS tips]
* xref:platform-file-split-or-not.adoc[.ios and .android files or platform conditionals?]
* xref:optimizing-images.adoc[Optimizing Images]
