= https://github.com/NativeScript/plugins/tree/main/packages/google-maps[Google Maps]

== @nativescript/google-maps

NativeScript binding for the Google Maps Android & iOS API.

== Prerequisites

To use the Google Maps API, you must register your app in the https://console.cloud.google.com/apis/dashboard[Google API Console] and obtain an API key.

== Installation

[,bash]
----
ns plugin add @nativescript/google-maps
----

== Config

=== Android

Modify the `AndroidManifest` to include the new meta tag along with your API key, the manifest is located in `App_Resources/Android/AndroidManifest.xml`

[,xml]
----
<application
  android:name="com.tns.NativeScriptApplication"
  android:allowBackup="true"
  android:icon="@mipmap/ic_launcher"
  android:label="@string/app_name"
  android:theme="@style/AppTheme"
  android:hardwareAccelerated="true"
>
  <meta-data android:name="com.google.android.geo.API_KEY" android:value="yourKey" />
</application>
----

=== iOS

Modify the `Info.plist` to include the new meta tag along with your API key, the manifest is located in `App_Resources/iOS/Info.plist`

[,xml]
----
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>TNSGoogleMapsAPIKey</key>
    <string>yourKey</string>
  </dict>
</plist>
----

== Usage

=== Core

[IMPORTANT]
====
Ensure you've included xmlns:map="@nativescript/google-maps" on the Page element
====

[,xml]
----
<map:MapView
  lat="{{lat}}"
  lng="{{lng}}"
  zoom="{{zoom}}"
  bearing="{{bearing}}"
  tilt="{{tilt}}"
  ready="{{onReady}}"
  mapTap="{{onTap}}"
  mapLongPress="{{onLongPress}}"
  markerTap="{{onMarkerTap}}"
/>
----

=== Angular

[tabs]
====
TypeScript::
+
[,ts]
----
import { GoogleMapsModule } from '@nativescript/google-maps/angular';

@NgModule({
    imports: [
      GoogleMapsModule
    ],
    declarations: [
      AppComponent
    ],
    bootstrap: [AppComponent]
})
----

HTML::
+
[,html]
----
<MapView
  (ready)="onReady($event)"
  (mapTap)="onTap($event)"
  (mapLongPress)="onLongPress($event)"
  (markerTap)="onMarkerTap($event)"
>
</MapView>
----
====

=== Vue

[tabs]
====
TypeScript::
+
[,ts]
----
import Vue from 'nativescript-vue'
import GoogleMaps from '@nativescript/google-maps/vue'

Vue.use(GoogleMaps)
----

HTML::
+
[,html]
----
<MapView
  @ready="onReady"
  @mapTap="onTap"
  @mapLongPress="onLongPress"
  @markerTap="onMarkerTap"
/>
----
====

== MapView API

=== Properties

The following properties are available for adjusting the camera view on initialization:

|===
| Property | type | Description and Data Type

| `lat`
| number
| Latitude, in degrees

| `lng`
| number
| Longitude, in degrees

| `zoom`
| number
| Zoom level (described https://developers.google.com/maps/documentation/javascript/tutorial#zoom-levels[here])

| `bearing`
| number
| Bearing, in degrees

| `tilt`
| number
| Tilt, in degrees
|===

=== Events

The following events are available:

|===
| Event | Description

| `ready`
| Fires when the MapView is ready for use see <<google-map,GoogleMap>>

| `mapTap`
| Fires when a coordinate is tapped on the map

| `mapLongPress`
| Fires when a coordinate is long-pressed on the map

| `markerTap`
| Fires when a marker is tapped

| `myLocationTap`
| Fires when 'My Location' is tapped

| `myLocationButtonTap`
| Fires when the 'My Location' button is tapped

| `markerDragStart`
| Fires when a marker begins dragging

| `markerDragging`
| Fires while a marker is being dragged

| `markerDragEnd`
| Fires when a marker ends dragging

| `tileRenderingStart`
| Fires when tile rendering begins

| `tileRenderingEnd`
| Fires when tile rendering ends

| `cameraPosition`
| Fires when the map viewport state changes, camera states include `idle` \| `start` \| `moving`

| `circle`
| Fires when a circle is tapped

| `polygon`
| Fires when a polygon is tapped

| `polyline`
| Fires when a polyline is tapped

| `poi`
| Fires when a POI is tapped

| `groundOverlay`
| Fires when a ground overlay is tapped

| `infoWindowTap`
| Fires when a marker's info window is tapped

| `infoWindowLongPress`
| Fires when a marker's info window is long-pressed

| `infoWindowClose`
| Fires when a marker's info window is closed

| `markerInfoContents`
|

| `markerInfoWindow`
|

| `activeBuilding`
| Fires when a building is focused on

| `activeLevel`
| Fires when the level of the focused building changes
|===

== Google Map

=== Instance

A GoogleMap instance is required from the map view to access many of the mapping features.
The GoogleMaps instance is available from the ``MapView``s `ready` event:

[,ts]
----
function onReady(event: MapReadyEvent) {
  const map: GoogleMap = event.map
}
----

=== API

==== Properties

|===
| Property | Type | Description

| `mapStyle`
| Style[]
| See <<map-styles,Map Styles>>

| `mapType`
| MapType
| See <<map-type,Map Type>>

| `buildingsEnabled`
| boolean
| Enables Buildings

| `maxZoomLevel`
| number
| Maximum level of zoom

| `minZoomLevel`
| number
| Minimum level of zoom

| `myLocationEnabled`
| boolean
| Enables "My Location"

| `trafficEnabled`
| boolean
| Enables traffic

| `uiSettings`
| IUISettings
| See <<UI Settings,UI Settings>>

| `cameraPosition`
| CameraPosition
| See <<Camera Position,Camera Position>>

| `projection`
| Projection
| See <<Projection,Projection>>
//TODO: add projection link
| `native`
| any
| See <<Native Map Object,Native Map Object>>
|===

==== Functions

|===
| Func | Description

| <<Adding Markers,addMarker>>(marker: <<Marker Options,MarkerOptions>>): <<Markers,Marker>>
| Adds a <<Markers,marker>> to the map

| <<Removing Markers,removeMarker>>(marker: <<Markers,Marker>>)
| Removes a marker from the map

| addTileOverlay(options: TileOverlayOptions): TileOverlay
| Adds a tile overlay to the map

| removeTileOverlay(overlay: TileOverlay)
| Removes a tile overlay from the map

| <<Adding Circles,addCircle>>(circle: <<Circle Options,CircleOptions>>): <<Circle,Circle>>
| Adds a circle to the map

| <<Removing Circles,removeCircle>>(circle: <<Circle,Circle>>)
| Removes a circle from the map

| addGroundOverlay(options: GroundOverlayOptions): GroundOverlay
| Adds a ground overlay to the map

| removeGroundOverlay(groundOverlay: GroundOverlay)
| Removes a ground overlay from the map

| <<Adding Polygons,addPolygon>>(options: <<Polygon Options,PolygonOptions>>): <<Polygons,Polygon>>
| Adds a polygon to the map

| <<Removing Polygons,removePolygon>>(polygon: <<Polygons,Polygon>>)
| Removes a polygon from the map

| <<Adding Polylines,addPolyline>>(options: <<Polyline Options,PolylineOptions>>): <<Polyline,Polyline>>
| Adds a polyline to the map

| <<Removing Polylines,removePolyline>>(polyline: link:[Polyline]#polyline)
| Removes a polyline from the map

| <<Controlling The Camera,animateCamera>>(update: CameraUpdate)
| Animates camera to a new position

| snapshot(): Promise<ImageSource>
| Returns a platform specific image of the maps current viewport

| clear()
| Clears all objects added to the map
|===

=== Native Map Object


`GoogleMap` gives you access to the platforms native map objects `native`| `android`| `ios`


Consult the appropriate SDK reference on how to use it: https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view[iOS] | https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap[Android]

=== Camera Position

The maps current camera position can be read from the ``GoogleMap``s object `cameraPosition`.

|===
| Property | Type | Description

| `target`
| Coordinate
| The camera target is the location of the center of the map, specified as `lat` and `lng`.

| `bearing`
| number
| The direction in which the camera points measured in degrees clockwise from north.

| `tilt`
| number
| The viewing angle of the camera measured in degrees

| `zoom`
| number
| The scale of the map
|===

==== Controlling The Camera

To programatically update the camera position you can call `animateCamera` from the `GoogleMap` object, like so:

[,ts]
----
import { CameraPosition } from '@nativescript/google-maps'

googleMap.animateCamera(
  CameraPosition.fromCoordinates(
    {
      lat: -32.1234,
      lng: 125.1234
    },
    googleMap.cameraPosition.zoom
  )
)
----

`CameraPosition` provides multiple methods to create a target CameraUpdate position.

|===
| Method | Description

| fromCoordinate(coordinate: Coordinate, zoom: number)
| Returns a CameraUpdate from a single coordinate

| fromCoordinates(coordinates: Coordinate[], padding: number)
| Returns a CameraUpdate from multiple coordinates

| fromCoordinates(coordinates: Coordinate[], width: number, height: number, padding: number)
| Returns a CameraUpdate from multiple coordinates with specified height, width and padding

| fromCameraPosition(position: CameraPosition)
| Returns a CameraUpdate from a CameraPosition

| zoomIn()
| Returns a CameraUpdate that has zoomed in

| zoomOut()
| Returns a CameraUpdate that has zoomed out

| zoomTo(value: number)
| Returns a CameraUpdate that has zoomed to a value

| zoomBy(amount: number, point?: { x: number;
y: number })
| Returns a CameraUpdate that has zoomed and panned

| scrollBy(x: number, y: number)
| Returns a panned CameraUpdate
|===

=== UI Settings

You can adjust the maps UI settings from the `GoogleMap` object by configuring the following properties of `uiSettings`:

|===
| Property | Type | Description

| `compassEnabled`
| boolean
| Whether the compass is enabled or not

| `indoorLevelPickerEnabled`
| boolean
| Whether the indoor level picker is enabled or not

| `mapToolbarEnabled`
| boolean
| Whether the map toolbar is enabled or not

| `myLocationButtonEnabled`
| boolean
| Whether the 'My Location' button is enabled or not

| `rotateGesturesEnabled`
| boolean
| Whether the compass is enabled or not

| `scrollGesturesEnabled`
| boolean
| Whether map scroll gestures are enabled or not

| `tiltGesturesEnabled`
| boolean
| Whether map tilt gestures are enabled or not

| `zoomGesturesEnabled`
| boolean
| Whether map zoom gestures are enabled or not

| `zoomControlsEnabled`
| boolean
| Whether map zoom controls are enabled or not

| `scrollGesturesEnabledDuringRotateOrZoom`
| boolean
| Whether scroll gestures are enabled while rotating or zooming
|===

=== Map Type

The Google Maps API offers five types of maps:

|===
| Type | Description

| `None`
| No tiles.
The map is rendered as an empty grid with no tiles loaded.

| `Normal`
| Typical road map.
Shows roads, some features built by humans, and important natural features such as rivers.
Road and feature labels are also visible.

| `Satellite`
| Satellite photograph data.
Road and feature labels are not visible.

| `Terrain`
| Topographic data.
The map includes colors, contour lines and labels, and perspective shading.
Some roads and labels are also visible.

| `Hybrid`
| Satellite photograph data with road maps added.
Road and feature labels are also visible.
|===

To set the type of a map, adjust the `GoogleMap` objects `mapType`.
You can pass in one map type from the `MapType` Enum.
For example:

[,ts]
----
import { GoogleMap, MapType } from '@nativescript/google-map';

...
map: GoogleMap;
map.mapType = MapType.Hybrid;
----

=== Map Styles

You can customize the presentation of the standard Google Map styles, changing the visual display of features like roads, parks, businesses, and other points of interest.
This means that you can emphasize particular components of the map or make the map look good with your app.

Styling works only on the `normal` map type.
Styling does not affect indoor maps.

To style your map, use a JSON file generated by the https://mapstyle.withgoogle.com[Google Maps APIs Styling Wizard].
In addition to changing the appearance of features, you can also hide features completely.

[,json]
----
[
  {
    "featureType": "all",
    "stylers": [{ "color": "#C0C0C0" }]
  },
  {
    "featureType": "road.arterial",
    "elementType": "geometry",
    "stylers": [{ "color": "#CCFFFF" }]
  },
  {
    "featureType": "landscape",
    "elementType": "labels",
    "stylers": [{ "visibility": "off" }]
  }
]
----

To apply a custom style to your map you can set the `mapStyle` property on your `GoogleMap` object, like so:

[,ts]
----
import { GoogleMap } from '@nativescript/google-map';

...
map: GoogleMap;
map.mapStyle = [{
	"featureType": "landscape",
	"elementType": "labels",
	"stylers": [
		{ "visibility": "off" }
	]
}];
----

== Markers

=== Adding Markers

You can create markers using the <<Google Map,GoogleMap>>s object `addMarker` function by passing in the specified <<Marker Options,Marker Options>>.

[,ts]
----
function addMarker(map: GoogleMap, markerOptions: MarkerOptions): Marker {
  return map.addMarker(markerOptions)
}
----

==== Marker Options

|===
| Property | Type | Description

| `position`
| Coordinate
| The position of the marker, specified as `lat` and `lng`

| `color`
| string \| Color
| Color of the marker, shades are unavailable.

| `title`
| string
| A string that's displayed in the info window when the user taps the marker

| `snippet`
| string
| Additional text that's displayed below the title

| `icon`
| Image
| A image that's displayed in place of the default marker image

| `draggable`
| boolean
| Set to `true` if you want to allow the user to move the marker.
Defaults to `false`

| `flat`
| boolean
| By default, markers are oriented against the screen, and will not rotate or tilt with the camera.
Flat markers are oriented against the surface of the earth, and will rotate and tilt with the camera

| `rotation`
| boolean
| The orientation of the marker, specified in degrees clockwise

| `anchorU`
| number
| Horizontal icon offset from the marker position

| `anchorV`
| number
| Vertical icon offset from the marker position

| `userData`
| any
| Additional information assigned to the marker

| `zIndex`
| number
| Z-index of the marker
|===

=== Removing Markers

You can remove a marker using the <<Google Map,GoogleMap>>s `removeMarker` function, like so:

[,ts]
----
function removeMarker(map: GoogleMap, marker: Marker) {
  map.removeMarker(marker)
}
----

== Circle

=== Adding Circles

You can create Circles using the <<Google Map,GoogleMap>>s object `addCircle` function by passing in the specified <<Circle Options,Circle Options>>.

[,ts]
----
function addCircle(map: GoogleMap, circleOptions: CircleOptions): Circle {
  return map.addCircle(circleOptions)
}
----

==== Circle Options

|===
| Property | Type

| `center`
| Coordinate

| `fillColor`
| Color \| string

| `radius`
| number

| `strokeColor`
| Color \| string

| `strokePattern`
| PatternItem & Partial<NativeObject>[]

| `strokeWidth`
| number

| `tappable`
| boolean

| `visible`
| boolean

| `zIndex`
| number

| `userData`
| `{ [key: string]: any }`
|===

=== Removing Circles

You can remove a Circle using the <<Google Map,GoogleMap>>s `removeCircle` function, like so:

[,ts]
----
function removeCircle(map: GoogleMap, circle: Circle) {
  map.removeCircle(circle)
}
----

== Polygons

=== Adding Polygons

You can create polygons using the <<Google Map,GoogleMap>>s object `addPolygon` function by passing in the specified <<Polygon Options,Polygon Options>>.

[,ts]
----
function addPolygon(map: GoogleMap, polygonOptions: PolygonOptions): Polygon {
  return map.addPolygon(polygonOptions)
}
----

==== Polygon Options

|===
| Property | Type

| `points`
| Coordinate[]

| `holes`
| Coordinate[]

| `tappable`
| boolean

| `strokeWidth`
| number

| `strokeColor`
| Color \| string

| `fillColor`
| Color \| string

| `strokePattern`
| PatternItem & Partial<NativeObject>[]

| `zIndex`
| number

| `geodesic`
| boolean

| `strokeJointType`
| JointType

| `visible`
| boolean

| `userData`
| `{ [key: string]: any }`
|===

=== Removing Polygons

You can remove a Polygon using the <<Google Map,GoogleMap>>s `removePolygon` function, like so:

[,ts]
----
function removePolygon(map: GoogleMap, polygon: Polygon) {
  map.removePolygon(polygon)
}
----

== Polyline

=== Adding Polylines

You can create Polylines using the <<Google Map,GoogleMap>>s object `addPolyline` function by passing in the specified <<Polyline Options,Polyline Options>>.

[,ts]
----
function addPolyline(map: GoogleMap, polylineOptions: PolylineOptions): Polyline {
  return map.addPolyline(polylineOptions)
}
----

==== Polyline Options

|===
| Property | Type

| `width`
| number

| `points`
| Coordinate[]

| `tappable`
| boolean

| `geodesic`
| boolean

| `visible`
| boolean

| `zIndex`
| number

| `jointType`
| JointType

| `pattern`
| PatternItem & Partial<NativeObject>[]

| `color`
| Color \| string

| `startCap`
| Cap & Partial<NativeObject>

| `endCap`
| Cap & Partial<NativeObject>

| `userData`
| `{ [key: string]: any }`
|===

=== Removing Polylines

You can remove a Polyline using the <<Google Map,GoogleMap>>s `removePolyline` function, like so:

[,ts]
----
function removePolyline(map: GoogleMap, polyline: Polyline) {
  map.removePolyline(polyline)
}
----

== Ground Overlays

=== Adding Ground Overlays

You can create Ground Overlays using the <<Google Map,GoogleMap>>s object `addGroundOverlay` function by passing in the specified <<GroundOverlay Options,GroundOverlay Options>>.

[,ts]
----
function addGroundOverlay(
  map: GoogleMap,
  groundOverlayOptions: GroundOverlayOptions
): GroundOverlay {
  return map.addGroundOverlay(groundOverlayOptions)
}
----

==== GroundOverlay Options

|===
| Property | Type

| `zIndex`
| number

| `visible`
| boolean

| `transparency`
| number

| `position`
| Coordinate

| `bounds`
| CoordinateBounds

| `tappable`
| boolean

| `bearing`
| number

| `image`
| ImageSource

| `userData`
| any

| `width`
| number

| `height`
| number

| `anchorU`
| number

| `anchorV`
| number
|===

=== Removing Ground Overlays

You can remove a GroundOverlay using the <<Google Map,GoogleMap>>s `removeGroundOverlay` function, like so:

[,ts]
----
function removeGroundOverlay(map: GoogleMap, groundOverlay: GroundOverlay) {
  map.removeGroundOverlay(groundOverlay)
}
----

== Tile Overlays

=== Adding Tile Overlays

You can create Tile Overlays using the <<Google Map,GoogleMap>>s object `addTileOverlay` function by passing in the specified <<TileOverlay Options,TileOverlay Options>>.

[,ts]
----
function addTileOverlay(
  map: GoogleMap,
  tileOverlayOptions: TileOverlayOptions
): TileOverlay {
  return map.addTileOverlay(tileOverlayOptions)
}
----

==== TileOverlay Options

|===
| Property | Type

| `fadeIn`
| boolean

| `transparency`
| number

| `visible`
| boolean

| `tileProvider`
| TileProvider & Partial<NativeObject>

| `zIndex`
| number
|===

=== Removing Tile Overlays

You can remove a TileOverlay using the <<Google Map,GoogleMaps>> `removeTileOverlay` function, like so:

[,ts]
----
function removeTileOverlay(map: GoogleMap, tileOverlay: TileOverlay) {
  map.removeTileOverlay(tileOverlay)
}
----
