:doctype: book

xref:README.adoc[NativeScript] / Exports

= NativeScript

== Table of contents

=== Namespaces

* xref:modules/CSSUtils.adoc[CSSUtils]
* xref:modules/CoreTypes.adoc[CoreTypes]
* xref:modules/DialogStrings.adoc[DialogStrings]
* xref:modules/GridUnitType.adoc[GridUnitType]
* xref:modules/IOSHelper.adoc[IOSHelper]
* xref:modules/Length.adoc[Length]
* xref:modules/PercentLength.adoc[PercentLength]
* xref:modules/TouchAction.adoc[TouchAction]
* xref:modules/Trace.adoc[Trace]
* xref:modules/capitalizationType.adoc[capitalizationType]
* xref:modules/encoding.adoc[encoding]
* xref:modules/inputType.adoc[inputType]
* xref:modules/knownFolders.adoc[knownFolders]
* xref:modules/path.adoc[path]

=== Enumerations

* xref:enums/AccessibilityLiveRegion.adoc[AccessibilityLiveRegion]
* xref:enums/AccessibilityRole.adoc[AccessibilityRole]
* xref:enums/AccessibilityState.adoc[AccessibilityState]
* xref:enums/AccessibilityTrait.adoc[AccessibilityTrait]
* xref:enums/CacheMode.adoc[CacheMode]
* xref:enums/FontScaleCategory.adoc[FontScaleCategory]
* xref:enums/GestureEvents.adoc[GestureEvents]
* xref:enums/GestureStateTypes.adoc[GestureStateTypes]
* xref:enums/GestureTypes.adoc[GestureTypes]
* xref:enums/HttpResponseEncoding.adoc[HttpResponseEncoding]
* xref:enums/SwipeDirection.adoc[SwipeDirection]

=== Classes

* xref:classes/AbsoluteLayout.adoc[AbsoluteLayout]
* xref:classes/ActionBar.adoc[ActionBar]
* xref:classes/ActionItem.adoc[ActionItem]
* xref:classes/ActionItems.adoc[ActionItems]
* xref:classes/ActivityIndicator.adoc[ActivityIndicator]
* xref:classes/AndroidApplication.adoc[AndroidApplication]
* xref:classes/Animation.adoc[Animation]
* xref:classes/Background.adoc[Background]
* xref:classes/Binding.adoc[Binding]
* xref:classes/Builder.adoc[Builder]
* xref:classes/Button.adoc[Button]
* xref:classes/ChangeType.adoc[ChangeType]
* xref:classes/CoercibleProperty.adoc[CoercibleProperty]
* xref:classes/Color.adoc[Color]
* xref:classes/ContainerView.adoc[ContainerView]
* xref:classes/ContentView.adoc[ContentView]
* xref:classes/ControlStateChangeListener.adoc[ControlStateChangeListener]
* xref:classes/CssAnimationParser.adoc[CssAnimationParser]
* xref:classes/CssAnimationProperty.adoc[CssAnimationProperty]
* xref:classes/CssProperty.adoc[CssProperty]
* xref:classes/CustomLayoutView.adoc[CustomLayoutView]
* xref:classes/DatePicker.adoc[DatePicker]
* xref:classes/DockLayout.adoc[DockLayout]
* xref:classes/EditableTextBase.adoc[EditableTextBase]
* xref:classes/File.adoc[File]
* xref:classes/FileSystemEntity.adoc[FileSystemEntity]
* xref:classes/FlexboxLayout.adoc[FlexboxLayout]
* xref:classes/Folder.adoc[Folder]
* xref:classes/Font.adoc[Font]
* xref:classes/FormattedString.adoc[FormattedString]
* xref:classes/Frame.adoc[Frame]
* xref:classes/GesturesObserver.adoc[GesturesObserver]
* xref:classes/GridLayout.adoc[GridLayout]
* xref:classes/HtmlView.adoc[HtmlView]
* xref:classes/Image.adoc[Image]
* xref:classes/ImageAsset.adoc[ImageAsset]
* xref:classes/ImageCache.adoc[ImageCache]
* xref:classes/ImageSource.adoc[ImageSource]
* xref:classes/InheritedCssProperty.adoc[InheritedCssProperty]
* xref:classes/InheritedProperty.adoc[InheritedProperty]
* xref:classes/ItemSpec.adoc[ItemSpec]
* xref:classes/KeyframeAnimation.adoc[KeyframeAnimation]
* xref:classes/KeyframeAnimationInfo.adoc[KeyframeAnimationInfo]
* xref:classes/KeyframeDeclaration.adoc[KeyframeDeclaration]
* xref:classes/KeyframeInfo.adoc[KeyframeInfo]
* xref:classes/Label.adoc[Label]
* xref:classes/LayoutBase.adoc[LayoutBase]
* xref:classes/ListPicker.adoc[ListPicker]
* xref:classes/ListView.adoc[ListView]
* xref:classes/ModuleNameResolver.adoc[ModuleNameResolver]
* xref:classes/NavigationButton.adoc[NavigationButton]
* xref:classes/Observable.adoc[Observable]
* xref:classes/ObservableArray.adoc[ObservableArray]
* xref:classes/Page.adoc[Page]
* xref:classes/PageBase.adoc[PageBase]
* xref:classes/ParserEvent.adoc[ParserEvent]
* xref:classes/ParserEventType.adoc[ParserEventType]
* xref:classes/Placeholder.adoc[Placeholder]
* xref:classes/Progress.adoc[Progress]
* xref:classes/Property.adoc[Property]
* xref:classes/ProxyViewContainer.adoc[ProxyViewContainer]
* xref:classes/Repeater.adoc[Repeater]
* xref:classes/RootLayout.adoc[RootLayout]
* xref:classes/Screen.adoc[Screen]
* xref:classes/ScrollView.adoc[ScrollView]
* xref:classes/SearchBar.adoc[SearchBar]
* xref:classes/SegmentedBar.adoc[SegmentedBar]
* xref:classes/SegmentedBarItem.adoc[SegmentedBarItem]
* xref:classes/ShorthandProperty.adoc[ShorthandProperty]
* xref:classes/Slider.adoc[Slider]
* xref:classes/Span.adoc[Span]
* xref:classes/StackLayout.adoc[StackLayout]
* xref:classes/Style.adoc[Style]
* xref:classes/Switch.adoc[Switch]
* xref:classes/TabView.adoc[TabView]
* xref:classes/TabViewItem.adoc[TabViewItem]
* xref:classes/TextBase.adoc[TextBase]
* xref:classes/TextField.adoc[TextField]
* xref:classes/TextView.adoc[TextView]
* xref:classes/TimePicker.adoc[TimePicker]
* xref:classes/TouchManager.adoc[TouchManager]
* xref:classes/Transition.adoc[Transition]
* xref:classes/View.adoc[View]
* xref:classes/ViewBase.adoc[ViewBase]
* xref:classes/ViewHelper.adoc[ViewHelper]
* xref:classes/VirtualArray.adoc[VirtualArray]
* xref:classes/WebView.adoc[WebView]
* xref:classes/WrapLayout.adoc[WrapLayout]
* xref:classes/WrappedValue.adoc[WrappedValue]
* xref:classes/XmlParser.adoc[XmlParser]
* xref:classes/iOSApplication.adoc[iOSApplication]

=== Interfaces

* xref:interfaces/ActionOptions.adoc[ActionOptions]
* xref:interfaces/AddArrayFromBuilder.adoc[AddArrayFromBuilder]
* xref:interfaces/AddChildFromBuilder.adoc[AddChildFromBuilder]
* xref:interfaces/AlertOptions.adoc[AlertOptions]
* xref:interfaces/AndroidActivityBackPressedEventData.adoc[AndroidActivityBackPressedEventData]
* xref:interfaces/AndroidActivityBundleEventData.adoc[AndroidActivityBundleEventData]
* xref:interfaces/AndroidActivityCallbacks.adoc[AndroidActivityCallbacks]
* xref:interfaces/AndroidActivityEventData.adoc[AndroidActivityEventData]
* xref:interfaces/AndroidActivityNewIntentEventData.adoc[AndroidActivityNewIntentEventData]
* xref:interfaces/AndroidActivityRequestPermissionsEventData.adoc[AndroidActivityRequestPermissionsEventData]
* xref:interfaces/AndroidActivityResultEventData.adoc[AndroidActivityResultEventData]
* xref:interfaces/AnimationDefinition.adoc[AnimationDefinition]
* xref:interfaces/ApplicationEventData.adoc[ApplicationEventData]
* xref:interfaces/BackstackEntry.adoc[BackstackEntry]
* xref:interfaces/BindingOptions.adoc[BindingOptions]
* xref:interfaces/CancelableOptions.adoc[CancelableOptions]
* xref:interfaces/ChangedData.adoc[ChangedData]
* xref:interfaces/CommonLayoutParams.adoc[CommonLayoutParams]
* xref:interfaces/ComponentModule.adoc[ComponentModule]
* xref:interfaces/ConfirmOptions.adoc[ConfirmOptions]
* xref:interfaces/CreateViewEventData.adoc[CreateViewEventData]
* xref:interfaces/CssChangedEventData.adoc[CssChangedEventData]
* xref:interfaces/DialogOptions.adoc[DialogOptions]
* xref:interfaces/DiscardedErrorEventData.adoc[DiscardedErrorEventData]
* xref:interfaces/DownloadError.adoc[DownloadError]
* xref:interfaces/DownloadRequest.adoc[DownloadRequest]
* xref:interfaces/DownloadedData.adoc[DownloadedData]
* xref:interfaces/EventData.adoc[EventData]
* xref:interfaces/GestureEventData.adoc[GestureEventData]
* xref:interfaces/GestureEventDataWithState.adoc[GestureEventDataWithState]
* xref:interfaces/HttpContent.adoc[HttpContent]
* xref:interfaces/HttpRequestOptions.adoc[HttpRequestOptions]
* xref:interfaces/HttpResponse.adoc[HttpResponse]
* xref:interfaces/IDevice.adoc[IDevice]
* xref:interfaces/ImageAssetOptions.adoc[ImageAssetOptions]
* xref:interfaces/ItemEventData.adoc[ItemEventData]
* xref:interfaces/ItemsLoading.adoc[ItemsLoading]
* xref:interfaces/ItemsSource.adoc[ItemsSource]
* xref:interfaces/KeyedTemplate.adoc[KeyedTemplate]
* xref:interfaces/LaunchEventData.adoc[LaunchEventData]
* xref:interfaces/LoadAppCSSEventData.adoc[LoadAppCSSEventData]
* xref:interfaces/LoadEventData.adoc[LoadEventData]
* xref:interfaces/LoadOptions.adoc[LoadOptions]
* xref:interfaces/LoginOptions.adoc[LoginOptions]
* xref:interfaces/LoginResult.adoc[LoginResult]
* xref:interfaces/NativeScriptConfig.adoc[NativeScriptConfig]
* xref:interfaces/NavigatedData.adoc[NavigatedData]
* xref:interfaces/NavigationContext.adoc[NavigationContext]
* xref:interfaces/NavigationEntry.adoc[NavigationEntry]
* xref:interfaces/NavigationTransition.adoc[NavigationTransition]
* xref:interfaces/OrientationChangedEventData.adoc[OrientationChangedEventData]
* xref:interfaces/PanGestureEventData.adoc[PanGestureEventData]
* xref:interfaces/PinchGestureEventData.adoc[PinchGestureEventData]
* xref:interfaces/PlatformContext.adoc[PlatformContext]
* xref:interfaces/PromptOptions.adoc[PromptOptions]
* xref:interfaces/PromptResult.adoc[PromptResult]
* xref:interfaces/PropertyChangeData.adoc[PropertyChangeData]
* xref:interfaces/RootLayoutOptions.adoc[RootLayoutOptions]
* xref:interfaces/RotationGestureEventData.adoc[RotationGestureEventData]
* xref:interfaces/ScrollEventData.adoc[ScrollEventData]
* xref:interfaces/ShadeCoverOptions.adoc[ShadeCoverOptions]
* xref:interfaces/ShowModalOptions.adoc[ShowModalOptions]
* xref:interfaces/ShownModallyData.adoc[ShownModallyData]
* xref:interfaces/Size.adoc[Size]
* xref:interfaces/SwipeGestureEventData.adoc[SwipeGestureEventData]
* xref:interfaces/SystemAppearanceChangedEventData.adoc[SystemAppearanceChangedEventData]
* xref:interfaces/TapGestureEventData.adoc[TapGestureEventData]
* xref:interfaces/Template.adoc[Template]
* xref:interfaces/TemplatedItemsView.adoc[TemplatedItemsView]
* xref:interfaces/TimerInfo.adoc[TimerInfo]
* xref:interfaces/TouchGestureEventData.adoc[TouchGestureEventData]
* xref:interfaces/TraceErrorHandler.adoc[TraceErrorHandler]
* xref:interfaces/TraceEventListener.adoc[TraceEventListener]
* xref:interfaces/TraceWriter.adoc[TraceWriter]
* xref:interfaces/UnhandledErrorEventData.adoc[UnhandledErrorEventData]
* xref:interfaces/ViewEntry.adoc[ViewEntry]

=== Type Aliases

* link:modules.md#gridunittype[GridUnitType]
* link:modules.md#headers[Headers]
* link:modules.md#horizontalalignment[HorizontalAlignment]
* link:modules.md#instrumentationmode[InstrumentationMode]
* link:modules.md#lengthdipunit[LengthDipUnit]
* link:modules.md#lengthpercentunit[LengthPercentUnit]
* link:modules.md#lengthpxunit[LengthPxUnit]
* link:modules.md#lengthtype[LengthType]
* link:modules.md#modulelistprovider[ModuleListProvider]
* link:modules.md#percentlengthtype[PercentLengthType]
* link:modules.md#touchanimationoptions[TouchAnimationOptions]
* link:modules.md#verticalalignment[VerticalAlignment]
* link:modules.md#webviewnavigationtype[WebViewNavigationType]
* link:modules.md#dip[dip]
* link:modules.md#percent[percent]
* link:modules.md#px[px]

=== Variables

* link:modules.md#accessibilityevents[AccessibilityEvents]
* link:modules.md#animationcurve[AnimationCurve]
* link:modules.md#application[Application]
* link:modules.md#applicationsettings[ApplicationSettings]
* link:modules.md#csshelper[CSSHelper]
* link:modules.md#connectivity[Connectivity]
* link:modules.md#device[Device]
* link:modules.md#dialogs[Dialogs]
* link:modules.md#enums[Enums]
* link:modules.md#http[Http]
* link:modules.md#utils[Utils]
* link:modules.md#androiddynamicelevationoffsetproperty[androidDynamicElevationOffsetProperty]
* link:modules.md#androidelevationproperty[androidElevationProperty]
* link:modules.md#autocapitalizationtypeproperty[autocapitalizationTypeProperty]
* link:modules.md#autocorrectproperty[autocorrectProperty]
* link:modules.md#backgroundcolorproperty[backgroundColorProperty]
* link:modules.md#backgroundimageproperty[backgroundImageProperty]
* link:modules.md#backgroundinternalproperty[backgroundInternalProperty]
* link:modules.md#backgroundpositionproperty[backgroundPositionProperty]
* link:modules.md#backgroundrepeatproperty[backgroundRepeatProperty]
* link:modules.md#backgroundsizeproperty[backgroundSizeProperty]
* link:modules.md#borderbottomcolorproperty[borderBottomColorProperty]
* link:modules.md#borderbottomleftradiusproperty[borderBottomLeftRadiusProperty]
* link:modules.md#borderbottomrightradiusproperty[borderBottomRightRadiusProperty]
* link:modules.md#borderbottomwidthproperty[borderBottomWidthProperty]
* link:modules.md#borderleftcolorproperty[borderLeftColorProperty]
* link:modules.md#borderleftwidthproperty[borderLeftWidthProperty]
* link:modules.md#borderrightcolorproperty[borderRightColorProperty]
* link:modules.md#borderrightwidthproperty[borderRightWidthProperty]
* link:modules.md#bordertopcolorproperty[borderTopColorProperty]
* link:modules.md#bordertopleftradiusproperty[borderTopLeftRadiusProperty]
* link:modules.md#bordertoprightradiusproperty[borderTopRightRadiusProperty]
* link:modules.md#bordertopwidthproperty[borderTopWidthProperty]
* link:modules.md#clippathproperty[clipPathProperty]
* link:modules.md#colorproperty[colorProperty]
* link:modules.md#editableproperty[editableProperty]
* link:modules.md#fontfamilyproperty[fontFamilyProperty]
* link:modules.md#fontinternalproperty[fontInternalProperty]
* link:modules.md#fontscaleproperty[fontScaleProperty]
* link:modules.md#fontsizeproperty[fontSizeProperty]
* link:modules.md#fontstyleproperty[fontStyleProperty]
* link:modules.md#fontweightproperty[fontWeightProperty]
* link:modules.md#heightproperty[heightProperty]
* link:modules.md#hintproperty[hintProperty]
* link:modules.md#horizontalalignmentproperty[horizontalAlignmentProperty]
* link:modules.md#isandroid[isAndroid]
* link:modules.md#isios[isIOS]
* link:modules.md#isuserinteractionenabledproperty[isUserInteractionEnabledProperty]
* link:modules.md#keyboardtypeproperty[keyboardTypeProperty]
* link:modules.md#letterspacingproperty[letterSpacingProperty]
* link:modules.md#lineheightproperty[lineHeightProperty]
* link:modules.md#marginbottomproperty[marginBottomProperty]
* link:modules.md#marginleftproperty[marginLeftProperty]
* link:modules.md#marginrightproperty[marginRightProperty]
* link:modules.md#margintopproperty[marginTopProperty]
* link:modules.md#maxlengthproperty[maxLengthProperty]
* link:modules.md#minheightproperty[minHeightProperty]
* link:modules.md#minwidthproperty[minWidthProperty]
* link:modules.md#opacityproperty[opacityProperty]
* link:modules.md#paddingbottomproperty[paddingBottomProperty]
* link:modules.md#paddingleftproperty[paddingLeftProperty]
* link:modules.md#paddingrightproperty[paddingRightProperty]
* link:modules.md#paddingtopproperty[paddingTopProperty]
* link:modules.md#perspectiveproperty[perspectiveProperty]
* link:modules.md#placeholdercolorproperty[placeholderColorProperty]
* link:modules.md#platformnames[platformNames]
* link:modules.md#profilingtime[profilingTime]
* link:modules.md#returnkeytypeproperty[returnKeyTypeProperty]
* link:modules.md#rotateproperty[rotateProperty]
* link:modules.md#rotatexproperty[rotateXProperty]
* link:modules.md#rotateyproperty[rotateYProperty]
* link:modules.md#scalexproperty[scaleXProperty]
* link:modules.md#scaleyproperty[scaleYProperty]
* link:modules.md#textalignmentproperty[textAlignmentProperty]
* link:modules.md#textdecorationproperty[textDecorationProperty]
* link:modules.md#textshadowproperty[textShadowProperty]
* link:modules.md#texttransformproperty[textTransformProperty]
* link:modules.md#translatexproperty[translateXProperty]
* link:modules.md#translateyproperty[translateYProperty]
* link:modules.md#unsetvalue[unsetValue]
* link:modules.md#updatetexttriggerproperty[updateTextTriggerProperty]
* link:modules.md#verticalalignmentproperty[verticalAlignmentProperty]
* link:modules.md#visibilityproperty[visibilityProperty]
* link:modules.md#whitespaceproperty[whiteSpaceProperty]
* link:modules.md#widthproperty[widthProperty]
* link:modules.md#zindexproperty[zIndexProperty]
* link:modules.md#zerolength[zeroLength]

=== Functions

* link:modules.md#csstype[CSSType]
* link:modules.md#pseudoclasshandler[PseudoClassHandler]
* link:modules.md#_setresolver[_setResolver]
* link:modules.md#_updatecharactersinrangereplacementstring[_updateCharactersInRangeReplacementString]
* link:modules.md#action[action]
* link:modules.md#addtaggedadditionalcss[addTaggedAdditionalCSS]
* link:modules.md#addweakeventlistener[addWeakEventListener]
* link:modules.md#alert[alert]
* link:modules.md#animationtimingfunctionconverter[animationTimingFunctionConverter]
* link:modules.md#booleanconverter[booleanConverter]
* link:modules.md#confirm[confirm]
* link:modules.md#eachdescendant[eachDescendant]
* link:modules.md#fromobject[fromObject]
* link:modules.md#fromobjectrecursive[fromObjectRecursive]
* link:modules.md#getancestor[getAncestor]
* link:modules.md#getcurrentpage[getCurrentPage]
* link:modules.md#getfileaccess[getFileAccess]
* link:modules.md#getrootlayout[getRootLayout]
* link:modules.md#gettransformedtext[getTransformedText]
* link:modules.md#getviewbyid[getViewById]
* link:modules.md#login[login]
* link:modules.md#makeparser[makeParser]
* link:modules.md#makevalidator[makeValidator]
* link:modules.md#parsecssshadow[parseCSSShadow]
* link:modules.md#parsekeyframedeclarations[parseKeyframeDeclarations]
* link:modules.md#profile[profile]
* link:modules.md#profilingdisable[profilingDisable]
* link:modules.md#profilingdumpprofiles[profilingDumpProfiles]
* link:modules.md#profilingenable[profilingEnable]
* link:modules.md#profilingisrunning[profilingIsRunning]
* link:modules.md#profilingresetprofiles[profilingResetProfiles]
* link:modules.md#profilingstart[profilingStart]
* link:modules.md#profilingstartcpu[profilingStartCPU]
* link:modules.md#profilingstop[profilingStop]
* link:modules.md#profilingstopcpu[profilingStopCPU]
* link:modules.md#profilinguptime[profilingUptime]
* link:modules.md#prompt[prompt]
* link:modules.md#removetaggedadditionalcss[removeTaggedAdditionalCSS]
* link:modules.md#removeweakeventlistener[removeWeakEventListener]
* link:modules.md#resolvefilenamefromurl[resolveFileNameFromUrl]
* link:modules.md#sanitizemodulename[sanitizeModuleName]
* link:modules.md#setactivitycallbacks[setActivityCallbacks]
* link:modules.md#timeconverter[timeConverter]
* link:modules.md#transformconverter[transformConverter]

== Type Aliases

[#gridunittype]
=== GridUnitType

Ƭ *GridUnitType*: `"pixel"` | `"star"` | `"auto"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/layouts/grid-layout/index.d.ts#L175[ui/layouts/grid-layout/index.d.ts:175]

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/layouts/grid-layout/index.d.ts#L176[ui/layouts/grid-layout/index.d.ts:176]

'''

[#headers]
=== Headers

Ƭ *Headers*: `Object`

==== Index signature

▪ [key: `string`]: `string` | `string`[]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/http/index.ts#L61[http/index.ts:61]

'''

[#horizontalalignment]
=== HorizontalAlignment

Ƭ *HorizontalAlignment*: link:modules/CoreTypes.md#horizontalalignmenttype[`HorizontalAlignmentType`]

*`Deprecated`*

Use `CoreTypes.HorizontalAlignmentType` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L326[core-types/index.ts:326]

'''

[#instrumentationmode]
=== InstrumentationMode

Ƭ *InstrumentationMode*: `"counters"` | `"timeline"` | `"lifecycle"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L16[profiling/index.ts:16]

'''

[#lengthdipunit]
=== LengthDipUnit

Ƭ *LengthDipUnit*: link:modules/CoreTypes.md#lengthdipunit[`LengthDipUnit`]

*`Deprecated`*

Use `CoreTypes.LengthDipUnit` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L299[core-types/index.ts:299]

'''

[#lengthpercentunit]
=== LengthPercentUnit

Ƭ *LengthPercentUnit*: link:modules/CoreTypes.md#lengthpercentunit[`LengthPercentUnit`]

*`Deprecated`*

Use `CoreTypes.LengthPercentUnit` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L307[core-types/index.ts:307]

'''

[#lengthpxunit]
=== LengthPxUnit

Ƭ *LengthPxUnit*: link:modules/CoreTypes.md#lengthpxunit[`LengthPxUnit`]

*`Deprecated`*

Use `CoreTypes.LengthPxUnit` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L303[core-types/index.ts:303]

'''

[#lengthtype]
=== LengthType

Ƭ *LengthType*: link:modules/CoreTypes.md#lengthtype[`LengthType`]

*`Deprecated`*

Use `CoreTypes.LengthType` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L312[core-types/index.ts:312]

'''

[#modulelistprovider]
=== ModuleListProvider

Ƭ *ModuleListProvider*: () \=> `string`[]

==== Type declaration

▸ (): `string`[]

===== Returns

`string`[]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/module-name-resolver/index.ts#L9[module-name-resolver/index.ts:9]

'''

[#percentlengthtype]
=== PercentLengthType

Ƭ *PercentLengthType*: link:modules/CoreTypes.md#percentlengthtype[`PercentLengthType`]

*`Deprecated`*

Use `CoreTypes.PercentLengthType` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L316[core-types/index.ts:316]

'''

[#touchanimationoptions]
=== TouchAnimationOptions

Ƭ *TouchAnimationOptions*: `Object`

==== Type declaration

|===
| Name | Type

| `down?`
| `TouchAnimationFn` \| `AnimationDefinition`

| `up?`
| `TouchAnimationFn` \| `AnimationDefinition`
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/touch-manager.ts#L13[ui/gestures/touch-manager.ts:13]

'''

[#verticalalignment]
=== VerticalAlignment

Ƭ *VerticalAlignment*: link:modules/CoreTypes.md#verticalalignmenttype[`VerticalAlignmentType`]

*`Deprecated`*

Use `CoreTypes.VerticalAlignmentType` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L331[core-types/index.ts:331]

'''

[#webviewnavigationtype]
=== WebViewNavigationType

Ƭ *WebViewNavigationType*: `"linkClicked"` | `"formSubmitted"` | `"backForward"` | `"reload"` | `"formResubmitted"` | `"other"` | `undefined`

Represents navigation type

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/web-view/index.d.ts#L17[ui/web-view/index.d.ts:17]

'''

[#dip]
=== dip

Ƭ *dip*: `number`

*`Deprecated`*

Use `CoreTypes.dip` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L284[core-types/index.ts:284]

'''

[#percent]
=== percent

Ƭ *percent*: `number`

*`Deprecated`*

Use `CoreTypes.percent` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L294[core-types/index.ts:294]

'''

[#px]
=== px

Ƭ *px*: `number`

*`Deprecated`*

Use `CoreTypes.px` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L289[core-types/index.ts:289]

== Variables

[#accessibilityevents]
=== AccessibilityEvents

• `Const` *AccessibilityEvents*: `Object`

==== Type declaration

|===
| Name | Type

| `accessibilityBlurEvent`
| `string`

| `accessibilityFocusChangedEvent`
| `string`

| `accessibilityFocusEvent`
| `string`
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/index.d.ts#L64[index.d.ts:64]

'''

[#animationcurve]
=== AnimationCurve

• `Const` *AnimationCurve*: typeof xref:modules/CoreTypes.AnimationCurve.adoc[`AnimationCurve`] = `CoreTypes.AnimationCurve`

*`Deprecated`*

Use `CoreTypes.AnimationCurve` instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L321[core-types/index.ts:321]

'''

[#application]
=== Application

• `Const` *Application*: `Object`

==== Type declaration

|===
| Name | Type

| `addCss`
| typeof `addCss`

| `android`
| xref:classes/AndroidApplication.adoc[`AndroidApplication`]

| `discardedErrorEvent`
| `string`

| `displayedEvent`
| `string`

| `exitEvent`
| `string`

| `fontScaleChangedEvent`
| `string`

| `getCssFileName`
| typeof `getCssFileName`

| `getMainEntry`
| typeof `getMainEntry`

| `getNativeApplication`
| typeof `getNativeApplication`

| `getResources`
| typeof `getResources`

| `getRootView`
| typeof `getRootView`

| `hasLaunched`
| typeof `hasLaunched`

| `hasListeners`
| typeof `hasListeners`

| `inBackground`
| `boolean`

| `ios`
| xref:classes/iOSApplication.adoc[`iOSApplication`]

| `launchEvent`
| `string`

| `loadAppCss`
| typeof `loadAppCss`

| `lowMemoryEvent`
| `string`

| `notify`
| typeof `notify`

| `off`
| typeof `off`

| `on`
| typeof `on`

| `orientation`
| typeof `orientation`

| `orientationChangedEvent`
| `string`

| `resetRootView`
| typeof `_resetRootView`

| `resumeEvent`
| `string`

| `run`
| typeof `run`

| `setAutoSystemAppearanceChanged`
| typeof `setAutoSystemAppearanceChanged`

| `setCssFileName`
| typeof `setCssFileName`

| `setMaxRefreshRate`
| typeof `setMaxRefreshRate`

| `setResources`
| typeof `setResources`

| `suspendEvent`
| `string`

| `suspended`
| `boolean`

| `systemAppearance`
| typeof `systemAppearance`

| `systemAppearanceChanged`
| typeof `systemAppearanceChanged`

| `systemAppearanceChangedEvent`
| `string`

| `uncaughtErrorEvent`
| `string`
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/index.d.ts#L12[index.d.ts:12]

'''

[#applicationsettings]
=== ApplicationSettings

• `Const` *ApplicationSettings*: `Object`

==== Type declaration

|===
| Name | Type

| `clear`
| typeof `clear`

| `flush`
| typeof `flush`

| `getAllKeys`
| typeof `getAllKeys`

| `getBoolean`
| typeof `getBoolean`

| `getNumber`
| typeof `getNumber`

| `getString`
| typeof `getString`

| `hasKey`
| typeof `hasKey`

| `remove`
| typeof `remove`

| `setBoolean`
| typeof `setBoolean`

| `setNumber`
| typeof `setNumber`

| `setString`
| typeof `setString`
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/index.d.ts#L51[index.d.ts:51]

'''

[#csshelper]
=== CSSHelper

• `Const` *CSSHelper*: `Object`

==== Type declaration

|===
| Name | Type

| `AttributeSelector`
| typeof `AttributeSelector`

| `ClassSelector`
| typeof `ClassSelector`

| `InvalidSelector`
| typeof `InvalidSelector`

| `PseudoClassSelector`
| typeof `PseudoClassSelector`

| `RuleSet`
| typeof `RuleSet`

| `Selector`
| typeof `Selector`

| `SelectorCore`
| typeof `SelectorCore`

| `SelectorsMap`
| typeof `SelectorsMap`

| `SelectorsMatch`
| typeof `SelectorsMatch`

| `SimpleSelector`
| typeof `SimpleSelector`

| `SimpleSelectorSequence`
| typeof `SimpleSelectorSequence`

| `TypeSelector`
| typeof `TypeSelector`

| `UniversalSelector`
| typeof `UniversalSelector`

| `createSelector`
| (`sel`: `string`) \=> `SimpleSelector` \| `SimpleSelectorSequence` \| `Selector`

| `fromAstNodes`
| (`astRules`: `Node`[]) \=> `RuleSet`[]
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/css-selector/index.ts#L702[ui/styling/css-selector/index.ts:702]

'''

[#connectivity]
=== Connectivity

• `Const` *Connectivity*: `Object`

==== Type declaration

|===
| Name | Type

| `connectionType`
| typeof `connectionType`

| `getConnectionType`
| typeof `getConnectionType`

| `startMonitoring`
| typeof `startMonitoring`

| `stopMonitoring`
| typeof `stopMonitoring`
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/index.d.ts#L72[index.d.ts:72]

'''

[#device]
=== Device

• `Const` *Device*: xref:interfaces/IDevice.adoc[`IDevice`]

Gets the current device information.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/platform/index.d.ts#L134[platform/index.d.ts:134]

'''

[#dialogs]
=== Dialogs

• `Const` *Dialogs*: `Object`

Singular rollup for convenience of all dialog methods

==== Type declaration

|===
| Name | Type

| `action`
| typeof link:modules.md#action[`action`]

| `alert`
| typeof link:modules.md#alert[`alert`]

| `confirm`
| typeof link:modules.md#confirm[`confirm`]

| `login`
| typeof link:modules.md#login[`login`]

| `prompt`
| typeof link:modules.md#prompt[`prompt`]
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L305[ui/dialogs/index.d.ts:305]

'''

[#enums]
=== Enums

• `Const` *Enums*: `Object`

*`Deprecated`*

Use `CoreTypes` instead.
Enums will be removed in 9.0

==== Type declaration

|===
| Name | Type

| `Accuracy`
| typeof xref:modules/CoreTypes.Accuracy.adoc[`Accuracy`]

| `AndroidActionBarIconVisibility`
| typeof xref:modules/CoreTypes.AndroidActionBarIconVisibility.adoc[`AndroidActionBarIconVisibility`]

| `AndroidActionItemPosition`
| typeof xref:modules/CoreTypes.AndroidActionItemPosition.adoc[`AndroidActionItemPosition`]

| `AnimationCurve`
| typeof xref:modules/CoreTypes.AnimationCurve.adoc[`AnimationCurve`]

| `AutocapitalizationType`
| typeof xref:modules/CoreTypes.AutocapitalizationType.adoc[`AutocapitalizationType`]

| `BackgroundRepeat`
| typeof xref:modules/CoreTypes.BackgroundRepeat.adoc[`BackgroundRepeat`]

| `DeviceOrientation`
| typeof xref:modules/CoreTypes.DeviceOrientation.adoc[`DeviceOrientation`]

| `DeviceType`
| typeof xref:modules/CoreTypes.DeviceType.adoc[`DeviceType`]

| `Dock`
| typeof xref:modules/CoreTypes.Dock.adoc[`Dock`]

| `FontAttributes`
| typeof xref:modules/CoreTypes.FontAttributes.adoc[`FontAttributes`]

| `FontStyle`
| typeof xref:modules/CoreTypes.FontStyle.adoc[`FontStyle`]

| `FontWeight`
| typeof xref:modules/CoreTypes.FontWeight.adoc[`FontWeight`]

| `HorizontalAlignment`
| typeof xref:modules/CoreTypes.HorizontalAlignment.adoc[`HorizontalAlignment`]

| `IOSActionItemPosition`
| typeof xref:modules/CoreTypes.IOSActionItemPosition.adoc[`IOSActionItemPosition`]

| `ImageFormat`
| typeof xref:modules/CoreTypes.ImageFormat.adoc[`ImageFormat`]

| `KeyboardType`
| typeof xref:modules/CoreTypes.KeyboardType.adoc[`KeyboardType`]

| `NavigationBarVisibility`
| typeof xref:modules/CoreTypes.NavigationBarVisibility.adoc[`NavigationBarVisibility`]

| `Orientation`
| typeof xref:modules/CoreTypes.Orientation.adoc[`Orientation`]

| `ReturnKeyType`
| typeof xref:modules/CoreTypes.ReturnKeyType.adoc[`ReturnKeyType`]

| `StatusBarStyle`
| typeof xref:modules/CoreTypes.StatusBarStyle.adoc[`StatusBarStyle`]

| `Stretch`
| typeof xref:modules/CoreTypes.ImageStretch.adoc[`ImageStretch`]

| `SystemAppearance`
| typeof xref:modules/CoreTypes.SystemAppearance.adoc[`SystemAppearance`]

| `TextAlignment`
| typeof xref:modules/CoreTypes.TextAlignment.adoc[`TextAlignment`]

| `TextDecoration`
| typeof xref:modules/CoreTypes.TextDecoration.adoc[`TextDecoration`]

| `TextTransform`
| typeof xref:modules/CoreTypes.TextTransform.adoc[`TextTransform`]

| `UpdateTextTrigger`
| typeof xref:modules/CoreTypes.UpdateTextTrigger.adoc[`UpdateTextTrigger`]

| `VerticalAlignment`
| typeof xref:modules/CoreTypes.VerticalAlignment.adoc[`VerticalAlignment`]

| `Visibility`
| typeof xref:modules/CoreTypes.Visibility.adoc[`Visibility`]

| `WhiteSpace`
| typeof xref:modules/CoreTypes.WhiteSpace.adoc[`WhiteSpace`]
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L336[core-types/index.ts:336]

'''

[#http]
=== Http

• `Const` *Http*: `Object`

==== Type declaration

|===
| Name | Type

| `getFile`
| typeof `getFile`

| `getImage`
| typeof `getImage`

| `getJSON`
| typeof `getJSON`

| `getString`
| typeof `httpGetString`

| `request`
| (`options`: `HttpRequestOptions`) \=> `Promise`<``HttpResponse``>
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/index.d.ts#L89[index.d.ts:89]

'''

[#utils]
=== Utils

• `Const` *Utils*: `Object`

==== Type declaration

|===
| Name | Type

| `ClassInfo`
| typeof `ClassInfo`

| `FILE_PREFIX`
| `string`

| `GC`
| typeof `GC`

| `RESOURCE_PREFIX`
| `string`

| `Source`
| typeof `Source`

| `ad`
| typeof `androidUtils`

| `android`
| typeof `androidUtils`

| `clearInterval`
| typeof `clearInterval`

| `clearTimeout`
| typeof `clearTimeout`

| `convertString`
| typeof `convertString`

| `dataDeserialize`
| typeof `dataDeserialize`

| `dataSerialize`
| typeof `dataSerialize`

| `debounce`
| typeof `debounce`

| `dismissSoftInput`
| typeof `dismissSoftInput`

| `dispatchToMainThread`
| typeof `dispatchToMainThread`

| `escapeRegexSymbols`
| typeof `escapeRegexSymbols`

| `executeOnMainThread`
| typeof `executeOnMainThread`

| `executeOnUIThread`
| typeof `executeOnUIThread`

| `getBaseClasses`
| typeof `getBaseClasses`

| `getClass`
| typeof `getClass`

| `getClassInfo`
| typeof `getClassInfo`

| `getModuleName`
| typeof `getModuleName`

| `ios`
| typeof `iosUtils`

| `isBoolean`
| typeof `isBoolean`

| `isDataURI`
| typeof `isDataURI`

| `isDefined`
| typeof `isDefined`

| `isFileOrResourcePath`
| typeof `isFileOrResourcePath`

| `isFontIconURI`
| typeof `isFontIconURI`

| `isFunction`
| typeof `isFunction`

| `isMainThread`
| typeof `isMainThread`

| `isNullOrUndefined`
| typeof `isNullOrUndefined`

| `isNumber`
| typeof `isNumber`

| `isObject`
| typeof `isObject`

| `isRealDevice`
| typeof `isRealDevice`

| `isString`
| typeof `isString`

| `isUndefined`
| typeof `isUndefined`

| `layout`
| typeof `layout`

| `mainThreadify`
| typeof `mainThreadify`

| `numberHasDecimals`
| typeof `numberHasDecimals`

| `numberIs64Bit`
| typeof `numberIs64Bit`

| `openFile`
| typeof `openFile`

| `openUrl`
| typeof `openUrl`

| `queueGC`
| typeof `queueGC`

| `queueMacrotask`
| typeof `queueMacrotask`

| `releaseNativeObject`
| typeof `releaseNativeObject`

| `setInterval`
| typeof `setInterval`

| `setTimeout`
| typeof `setTimeout`

| `throttle`
| typeof `throttle`

| `toUIString`
| typeof `toUIString`

| `verifyCallback`
| typeof `verifyCallback`
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/index.d.ts#L110[index.d.ts:110]

'''

[#androiddynamicelevationoffsetproperty]
=== androidDynamicElevationOffsetProperty

• `Const` *androidDynamicElevationOffsetProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1450[ui/styling/style-properties.ts:1450]

'''

[#androidelevationproperty]
=== androidElevationProperty

• `Const` *androidElevationProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1443[ui/styling/style-properties.ts:1443]

'''

[#autocapitalizationtypeproperty]
=== autocapitalizationTypeProperty

• `Const` *autocapitalizationTypeProperty*: xref:classes/Property.adoc[`Property`]<xref:classes/EditableTextBase.adoc[`EditableTextBase`], link:modules/CoreTypes.md#autocapitalizationinputtype[`AutocapitalizationInputType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/editable-text-base/index.d.ts#L83[ui/editable-text-base/index.d.ts:83]

'''

[#autocorrectproperty]
=== autocorrectProperty

• `Const` *autocorrectProperty*: xref:classes/Property.adoc[`Property`]<xref:classes/EditableTextBase.adoc[`EditableTextBase`], `boolean`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/editable-text-base/index.d.ts#L84[ui/editable-text-base/index.d.ts:84]

'''

[#backgroundcolorproperty]
=== backgroundColorProperty

• `Const` *backgroundColorProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], xref:classes/Color.adoc[`Color`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L799[ui/styling/style-properties.ts:799]

'''

[#backgroundimageproperty]
=== backgroundImageProperty

• `Const` *backgroundImageProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], `string` | `LinearGradient`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L773[ui/styling/style-properties.ts:773]

'''

[#backgroundinternalproperty]
=== backgroundInternalProperty

• `Const` *backgroundInternalProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], xref:classes/Background.adoc[`Background`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L765[ui/styling/style-properties.ts:765]

'''

[#backgroundpositionproperty]
=== backgroundPositionProperty

• `Const` *backgroundPositionProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], `string`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L829[ui/styling/style-properties.ts:829]

'''

[#backgroundrepeatproperty]
=== backgroundRepeatProperty

• `Const` *backgroundRepeatProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#backgroundrepeattype[`BackgroundRepeatType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L810[ui/styling/style-properties.ts:810]

'''

[#backgroundsizeproperty]
=== backgroundSizeProperty

• `Const` *backgroundSizeProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], `string`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L820[ui/styling/style-properties.ts:820]

'''

[#borderbottomcolorproperty]
=== borderBottomColorProperty

• `Const` *borderBottomColorProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], xref:classes/Color.adoc[`Color`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L978[ui/styling/style-properties.ts:978]

'''

[#borderbottomleftradiusproperty]
=== borderBottomLeftRadiusProperty

• `Const` *borderBottomLeftRadiusProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1210[ui/styling/style-properties.ts:1210]

'''

[#borderbottomrightradiusproperty]
=== borderBottomRightRadiusProperty

• `Const` *borderBottomRightRadiusProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1194[ui/styling/style-properties.ts:1194]

'''

[#borderbottomwidthproperty]
=== borderBottomWidthProperty

• `Const` *borderBottomWidthProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1081[ui/styling/style-properties.ts:1081]

'''

[#borderleftcolorproperty]
=== borderLeftColorProperty

• `Const` *borderLeftColorProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], xref:classes/Color.adoc[`Color`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L989[ui/styling/style-properties.ts:989]

'''

[#borderleftwidthproperty]
=== borderLeftWidthProperty

• `Const` *borderLeftWidthProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1105[ui/styling/style-properties.ts:1105]

'''

[#borderrightcolorproperty]
=== borderRightColorProperty

• `Const` *borderRightColorProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], xref:classes/Color.adoc[`Color`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L967[ui/styling/style-properties.ts:967]

'''

[#borderrightwidthproperty]
=== borderRightWidthProperty

• `Const` *borderRightWidthProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1057[ui/styling/style-properties.ts:1057]

'''

[#bordertopcolorproperty]
=== borderTopColorProperty

• `Const` *borderTopColorProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], xref:classes/Color.adoc[`Color`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L956[ui/styling/style-properties.ts:956]

'''

[#bordertopleftradiusproperty]
=== borderTopLeftRadiusProperty

• `Const` *borderTopLeftRadiusProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1162[ui/styling/style-properties.ts:1162]

'''

[#bordertoprightradiusproperty]
=== borderTopRightRadiusProperty

• `Const` *borderTopRightRadiusProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1178[ui/styling/style-properties.ts:1178]

'''

[#bordertopwidthproperty]
=== borderTopWidthProperty

• `Const` *borderTopWidthProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1033[ui/styling/style-properties.ts:1033]

'''

[#clippathproperty]
=== clipPathProperty

• `Const` *clipPathProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], `string`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1252[ui/styling/style-properties.ts:1252]

'''

[#colorproperty]
=== colorProperty

• `Const` *colorProperty*: xref:classes/InheritedCssProperty.adoc[`InheritedCssProperty`]<xref:classes/Style.adoc[`Style`], xref:classes/Color.adoc[`Color`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1298[ui/styling/style-properties.ts:1298]

'''

[#editableproperty]
=== editableProperty

• `Const` *editableProperty*: xref:classes/Property.adoc[`Property`]<xref:classes/EditableTextBase.adoc[`EditableTextBase`], `boolean`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/editable-text-base/index.d.ts#L81[ui/editable-text-base/index.d.ts:81]

'''

[#fontfamilyproperty]
=== fontFamilyProperty

• `Const` *fontFamilyProperty*: xref:classes/InheritedCssProperty.adoc[`InheritedCssProperty`]<xref:classes/Style.adoc[`Style`], `string`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1312[ui/styling/style-properties.ts:1312]

'''

[#fontinternalproperty]
=== fontInternalProperty

• `Const` *fontInternalProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], xref:classes/Font.adoc[`Font`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1306[ui/styling/style-properties.ts:1306]

'''

[#fontscaleproperty]
=== fontScaleProperty

• `Const` *fontScaleProperty*: xref:classes/InheritedCssProperty.adoc[`InheritedCssProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1326[ui/styling/style-properties.ts:1326]

'''

[#fontsizeproperty]
=== fontSizeProperty

• `Const` *fontSizeProperty*: xref:classes/InheritedCssProperty.adoc[`InheritedCssProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1347[ui/styling/style-properties.ts:1347]

'''

[#fontstyleproperty]
=== fontStyleProperty

• `Const` *fontStyleProperty*: xref:classes/InheritedCssProperty.adoc[`InheritedCssProperty`]<xref:classes/Style.adoc[`Style`], `FontStyle`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1365[ui/styling/style-properties.ts:1365]

'''

[#fontweightproperty]
=== fontWeightProperty

• `Const` *fontWeightProperty*: xref:classes/InheritedCssProperty.adoc[`InheritedCssProperty`]<xref:classes/Style.adoc[`Style`], `FontWeight`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1381[ui/styling/style-properties.ts:1381]

'''

[#heightproperty]
=== heightProperty

• `Const` *heightProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#percentlengthtype[`PercentLengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L244[ui/styling/style-properties.ts:244]

'''

[#hintproperty]
=== hintProperty

• `Const` *hintProperty*: xref:classes/Property.adoc[`Property`]<xref:classes/EditableTextBase.adoc[`EditableTextBase`], `string`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/editable-text-base/index.d.ts#L85[ui/editable-text-base/index.d.ts:85]

'''

[#horizontalalignmentproperty]
=== horizontalAlignmentProperty

• `Const` *horizontalAlignmentProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#horizontalalignmenttype[`HorizontalAlignmentType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L403[ui/styling/style-properties.ts:403]

'''

[#isandroid]
=== isAndroid

• `Const` *isAndroid*: `boolean`

Gets a value indicating if the app is running on the Android platform.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/platform/index.d.ts#L10[platform/index.d.ts:10]

'''

[#isios]
=== isIOS

• `Const` *isIOS*: `boolean`

Gets a value indicating if the app is running on the iOS platform.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/platform/index.d.ts#L15[platform/index.d.ts:15]

'''

[#isuserinteractionenabledproperty]
=== isUserInteractionEnabledProperty

• `Const` *isUserInteractionEnabledProperty*: xref:classes/Property.adoc[`Property`]<xref:classes/View.adoc[`View`], `boolean`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/view/index.d.ts#L973[ui/core/view/index.d.ts:973]

'''

[#keyboardtypeproperty]
=== keyboardTypeProperty

• `Const` *keyboardTypeProperty*: xref:classes/Property.adoc[`Property`]<xref:classes/EditableTextBase.adoc[`EditableTextBase`], link:modules/CoreTypes.md#keyboardinputtype[`KeyboardInputType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/editable-text-base/index.d.ts#L79[ui/editable-text-base/index.d.ts:79]

'''

[#letterspacingproperty]
=== letterSpacingProperty

• `Const` *letterSpacingProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/text-base/index.d.ts#L137[ui/text-base/index.d.ts:137]

'''

[#lineheightproperty]
=== lineHeightProperty

• `Const` *lineHeightProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/text-base/index.d.ts#L138[ui/text-base/index.d.ts:138]

'''

[#marginbottomproperty]
=== marginBottomProperty

• `Const` *marginBottomProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#percentlengthtype[`PercentLengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L307[ui/styling/style-properties.ts:307]

'''

[#marginleftproperty]
=== marginLeftProperty

• `Const` *marginLeftProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#percentlengthtype[`PercentLengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L277[ui/styling/style-properties.ts:277]

'''

[#marginrightproperty]
=== marginRightProperty

• `Const` *marginRightProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#percentlengthtype[`PercentLengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L287[ui/styling/style-properties.ts:287]

'''

[#margintopproperty]
=== marginTopProperty

• `Const` *marginTopProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#percentlengthtype[`PercentLengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L297[ui/styling/style-properties.ts:297]

'''

[#maxlengthproperty]
=== maxLengthProperty

• `Const` *maxLengthProperty*: xref:classes/Property.adoc[`Property`]<xref:classes/EditableTextBase.adoc[`EditableTextBase`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/editable-text-base/index.d.ts#L87[ui/editable-text-base/index.d.ts:87]

'''

[#minheightproperty]
=== minHeightProperty

• `Const` *minHeightProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L207[ui/styling/style-properties.ts:207]

'''

[#minwidthproperty]
=== minWidthProperty

• `Const` *minWidthProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L189[ui/styling/style-properties.ts:189]

'''

[#opacityproperty]
=== opacityProperty

• `Const` *opacityProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1290[ui/styling/style-properties.ts:1290]

'''

[#paddingbottomproperty]
=== paddingBottomProperty

• `Const` *paddingBottomProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L385[ui/styling/style-properties.ts:385]

'''

[#paddingleftproperty]
=== paddingLeftProperty

• `Const` *paddingLeftProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L331[ui/styling/style-properties.ts:331]

'''

[#paddingrightproperty]
=== paddingRightProperty

• `Const` *paddingRightProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L349[ui/styling/style-properties.ts:349]

'''

[#paddingtopproperty]
=== paddingTopProperty

• `Const` *paddingTopProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#lengthtype[`LengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L367[ui/styling/style-properties.ts:367]

'''

[#perspectiveproperty]
=== perspectiveProperty

• `Const` *perspectiveProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L536[ui/styling/style-properties.ts:536]

'''

[#placeholdercolorproperty]
=== placeholderColorProperty

• `Const` *placeholderColorProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], xref:classes/Color.adoc[`Color`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/editable-text-base/index.d.ts#L86[ui/editable-text-base/index.d.ts:86]

'''

[#platformnames]
=== platformNames

• `Const` *platformNames*: `Object`

==== Type declaration

|===
| Name | Type

| `android`
| `string`

| `ios`
| `string`
|===

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/platform/index.d.ts#L20[platform/index.d.ts:20]

'''

[#profilingtime]
=== profilingTime

• `Const` *profilingTime*: `any`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L34[profiling/index.ts:34]

'''

[#returnkeytypeproperty]
=== returnKeyTypeProperty

• `Const` *returnKeyTypeProperty*: xref:classes/Property.adoc[`Property`]<xref:classes/EditableTextBase.adoc[`EditableTextBase`], link:modules/CoreTypes.md#returnkeybuttontype[`ReturnKeyButtonType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/editable-text-base/index.d.ts#L80[ui/editable-text-base/index.d.ts:80]

'''

[#rotateproperty]
=== rotateProperty

• `Const` *rotateProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L512[ui/styling/style-properties.ts:512]

'''

[#rotatexproperty]
=== rotateXProperty

• `Const` *rotateXProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L520[ui/styling/style-properties.ts:520]

'''

[#rotateyproperty]
=== rotateYProperty

• `Const` *rotateYProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L528[ui/styling/style-properties.ts:528]

'''

[#scalexproperty]
=== scaleXProperty

• `Const` *scaleXProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L544[ui/styling/style-properties.ts:544]

'''

[#scaleyproperty]
=== scaleYProperty

• `Const` *scaleYProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L552[ui/styling/style-properties.ts:552]

'''

[#textalignmentproperty]
=== textAlignmentProperty

• `Const` *textAlignmentProperty*: xref:classes/InheritedCssProperty.adoc[`InheritedCssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#textalignmenttype[`TextAlignmentType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/text-base/index.d.ts#L132[ui/text-base/index.d.ts:132]

'''

[#textdecorationproperty]
=== textDecorationProperty

• `Const` *textDecorationProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#textdecorationtype[`TextDecorationType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/text-base/index.d.ts#L133[ui/text-base/index.d.ts:133]

'''

[#textshadowproperty]
=== textShadowProperty

• `Const` *textShadowProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], `CSSShadow`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/text-base/index.d.ts#L135[ui/text-base/index.d.ts:135]

'''

[#texttransformproperty]
=== textTransformProperty

• `Const` *textTransformProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#texttransformtype[`TextTransformType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/text-base/index.d.ts#L134[ui/text-base/index.d.ts:134]

'''

[#translatexproperty]
=== translateXProperty

• `Const` *translateXProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L568[ui/styling/style-properties.ts:568]

'''

[#translateyproperty]
=== translateYProperty

• `Const` *translateYProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L576[ui/styling/style-properties.ts:576]

'''

[#unsetvalue]
=== unsetValue

• `Const` *unsetValue*: `any`

Value specifying that Property should be set to its initial value.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/properties/index.ts#L14[ui/core/properties/index.ts:14]

'''

[#updatetexttriggerproperty]
=== updateTextTriggerProperty

• `Const` *updateTextTriggerProperty*: xref:classes/Property.adoc[`Property`]<xref:classes/EditableTextBase.adoc[`EditableTextBase`], link:modules/CoreTypes.md#updatetexttriggertype[`UpdateTextTriggerType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/editable-text-base/index.d.ts#L82[ui/editable-text-base/index.d.ts:82]

'''

[#verticalalignmentproperty]
=== verticalAlignmentProperty

• `Const` *verticalAlignmentProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#verticalalignmenttexttype[`VerticalAlignmentTextType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L412[ui/styling/style-properties.ts:412]

'''

[#visibilityproperty]
=== visibilityProperty

• `Const` *visibilityProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#visibilitytype[`VisibilityType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1426[ui/styling/style-properties.ts:1426]

'''

[#whitespaceproperty]
=== whiteSpaceProperty

• `Const` *whiteSpaceProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#whitespacetype[`WhiteSpaceType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/text-base/index.d.ts#L136[ui/text-base/index.d.ts:136]

'''

[#widthproperty]
=== widthProperty

• `Const` *widthProperty*: xref:classes/CssAnimationProperty.adoc[`CssAnimationProperty`]<xref:classes/Style.adoc[`Style`], link:modules/CoreTypes.md#percentlengthtype[`PercentLengthType`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L225[ui/styling/style-properties.ts:225]

'''

[#zindexproperty]
=== zIndexProperty

• `Const` *zIndexProperty*: xref:classes/CssProperty.adoc[`CssProperty`]<xref:classes/Style.adoc[`Style`], `number`>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L1274[ui/styling/style-properties.ts:1274]

'''

[#zerolength]
=== zeroLength

• `Const` *zeroLength*: link:modules/CoreTypes.md#lengthtype[`LengthType`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L187[ui/styling/style-properties.ts:187]

== Functions

[#csstype]
=== CSSType

▸ *CSSType*(`type`): `ClassDecorator`

Specifies the type name for the instances of this View class, that is used when matching CSS type selectors.

Usage:

----
@CSSType("Button")
class Button extends View {
}
----

Internally the decorator set `Button.prototype.cssType = "Button"`.

==== Parameters

|===
| Name | Type | Description

| `type`
| `string`
| The type name, e.
g.
"Button", "Label", etc.
|===

==== Returns

`ClassDecorator`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/view/index.d.ts#L36[ui/core/view/index.d.ts:36]

'''

[#pseudoclasshandler]
=== PseudoClassHandler

▸ *PseudoClassHandler*(...`pseudoClasses`): `MethodDecorator`

==== Parameters

|===
| Name | Type

| `+...pseudoClasses+`
| `string`[]
|===

==== Returns

`MethodDecorator`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/view/index.d.ts#L20[ui/core/view/index.d.ts:20]

'''

[#_setresolver]
=== _setResolver

▸ *_setResolver*(`resolver`): `void`

==== Parameters

|===
| Name | Type

| `resolver`
| xref:classes/ModuleNameResolver.adoc[`ModuleNameResolver`]
|===

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/module-name-resolver/index.ts#L94[module-name-resolver/index.ts:94]

'''

[#_updatecharactersinrangereplacementstring]
=== _updateCharactersInRangeReplacementString

▸ `Private` *_updateCharactersInRangeReplacementString*(`formattedText`, `rangeLocation`, `rangeLength`, `replacementString`): `void`

==== Parameters

|===
| Name | Type

| `formattedText`
| xref:classes/FormattedString.adoc[`FormattedString`]

| `rangeLocation`
| `number`

| `rangeLength`
| `number`

| `replacementString`
| `string`
|===

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/editable-text-base/index.d.ts#L93[ui/editable-text-base/index.d.ts:93]

'''

[#action]
=== action

▸ *action*(`message`, `cancelButtonText`, `actions`): `Promise`<``string``>

The action() method displays a action box that prompts the visitor to choose some action.

==== Parameters

|===
| Name | Type | Description

| `message`
| `string`
| The text to display in the dialog box.

| `cancelButtonText`
| `string`
| The text to display in the cancel button.

| `actions`
| `string`[]
| List of available actions.
|===

==== Returns

`Promise`<``string``>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L129[ui/dialogs/index.d.ts:129]

▸ *action*(`options`): `Promise`<``string``>

The action() method displays a action box that prompts the visitor to choose some action.

==== Parameters

|===
| Name | Type | Description

| `options`
| xref:interfaces/ActionOptions.adoc[`ActionOptions`]
| The options for the dialog box.
|===

==== Returns

`Promise`<``string``>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L135[ui/dialogs/index.d.ts:135]

'''

[#addtaggedadditionalcss]
=== addTaggedAdditionalCSS

▸ *addTaggedAdditionalCSS*(`cssText`, `tag?`): `boolean`

==== Parameters

|===
| Name | Type

| `cssText`
| `string`

| `tag?`
| `string` \| `number`
|===

==== Returns

`boolean`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-scope.ts#L315[ui/styling/style-scope.ts:315]

'''

[#addweakeventlistener]
=== addWeakEventListener

▸ *addWeakEventListener*(`source`, `eventName`, `handler`, `target`): `void`

==== Parameters

|===
| Name | Type

| `source`
| xref:classes/Observable.adoc[`Observable`]

| `eventName`
| `string`

| `handler`
| (`eventData`: xref:interfaces/EventData.adoc[`EventData`]) \=> `void`

| `target`
| `any`
|===

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/weak-event-listener/index.ts#L81[ui/core/weak-event-listener/index.ts:81]

'''

[#alert]
=== alert

▸ *alert*(`message`): `Promise`<``void``>

The alert() method displays an alert box with a specified message.

==== Parameters

|===
| Name | Type | Description

| `message`
| `string` \| `number` \| `boolean`
| Specifies the text to display in the alert box.
|===

==== Returns

`Promise`<``void``>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L66[ui/dialogs/index.d.ts:66]

▸ *alert*(`options`): `Promise`<``void``>

The alert() method displays an alert box with a specified message.

==== Parameters

|===
| Name | Type | Description

| `options`
| xref:interfaces/AlertOptions.adoc[`AlertOptions`]
| Specifies the options for the alert box.
|===

==== Returns

`Promise`<``void``>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L72[ui/dialogs/index.d.ts:72]

'''

[#animationtimingfunctionconverter]
=== animationTimingFunctionConverter

▸ *animationTimingFunctionConverter*(`value`): `any`

==== Parameters

|===
| Name | Type

| `value`
| `string`
|===

==== Returns

`any`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/converters.ts#L21[ui/styling/converters.ts:21]

'''

[#booleanconverter]
=== booleanConverter

▸ *booleanConverter*(`v`): `boolean`

==== Parameters

|===
| Name | Type

| `v`
| `string`
|===

==== Returns

`boolean`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/view-base/index.ts#L1215[ui/core/view-base/index.ts:1215]

'''

[#confirm]
=== confirm

▸ *confirm*(`message`): `Promise`<``boolean``>

The confirm() method displays a dialog box with a specified message.

==== Parameters

|===
| Name | Type | Description

| `message`
| `string`
| Specifies the text to display in the confirm box.
|===

==== Returns

`Promise`<``boolean``>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L78[ui/dialogs/index.d.ts:78]

▸ *confirm*(`options`): `Promise`<``boolean``>

The confirm() method displays a dialog box with a specified message.

==== Parameters

|===
| Name | Type | Description

| `options`
| xref:interfaces/ConfirmOptions.adoc[`ConfirmOptions`]
| Specifies the options for the confirm box.
|===

==== Returns

`Promise`<``boolean``>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L84[ui/dialogs/index.d.ts:84]

'''

[#eachdescendant]
=== eachDescendant

▸ *eachDescendant*(`view`, `callback`): `void`

==== Parameters

|===
| Name | Type

| `view`
| xref:classes/ViewBase.adoc[`ViewBase`]

| `callback`
| (`child`: xref:classes/ViewBase.adoc[`ViewBase`]) \=> `boolean`
|===

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/view-base/index.ts#L173[ui/core/view-base/index.ts:173]

'''

[#fromobject]
=== fromObject

▸ *fromObject*(`source`): xref:classes/Observable.adoc[`Observable`]

==== Parameters

|===
| Name | Type

| `source`
| `any`
|===

==== Returns

xref:classes/Observable.adoc[`Observable`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/data/observable/index.ts#L408[data/observable/index.ts:408]

'''

[#fromobjectrecursive]
=== fromObjectRecursive

▸ *fromObjectRecursive*(`source`): xref:classes/Observable.adoc[`Observable`]

==== Parameters

|===
| Name | Type

| `source`
| `any`
|===

==== Returns

xref:classes/Observable.adoc[`Observable`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/data/observable/index.ts#L415[data/observable/index.ts:415]

'''

[#getancestor]
=== getAncestor

▸ *getAncestor*(`view`, `criterion`): xref:classes/ViewBase.adoc[`ViewBase`]

==== Parameters

|===
| Name | Type

| `view`
| xref:classes/ViewBase.adoc[`ViewBase`]

| `criterion`
| `string` \| () \=> `any`
|===

==== Returns

xref:classes/ViewBase.adoc[`ViewBase`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/view-base/index.ts#L104[ui/core/view-base/index.ts:104]

'''

[#getcurrentpage]
=== getCurrentPage

▸ *getCurrentPage*(): xref:classes/Page.adoc[`Page`]

==== Returns

xref:classes/Page.adoc[`Page`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/dialogs-common.ts#L243[ui/dialogs/dialogs-common.ts:243]

'''

[#getfileaccess]
=== getFileAccess

▸ *getFileAccess*(): `IFileSystemAccess`

Returns FileSystemAccess, a shared singleton utility class to provide methods to access and work with the file system.
This is used under the hood of all the file system apis in @nativescript/core and provided as a lower level convenience if needed.

==== Returns

`IFileSystemAccess`

FileSystemAccess

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/file-system/index.ts#L10[file-system/index.ts:10]

'''

[#getrootlayout]
=== getRootLayout

▸ *getRootLayout*(): xref:classes/RootLayout.adoc[`RootLayout`]

==== Returns

xref:classes/RootLayout.adoc[`RootLayout`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/layouts/root-layout/index.d.ts#L15[ui/layouts/root-layout/index.d.ts:15]

'''

[#gettransformedtext]
=== getTransformedText

▸ *getTransformedText*(`text`, `textTransform`): `string`

==== Parameters

|===
| Name | Type

| `text`
| `string`

| `textTransform`
| link:modules/CoreTypes.md#texttransformtype[`TextTransformType`]
|===

==== Returns

`string`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/text-base/index.d.ts#L141[ui/text-base/index.d.ts:141]

'''

[#getviewbyid]
=== getViewById

▸ *getViewById*(`view`, `id`): xref:classes/ViewBase.adoc[`ViewBase`]

==== Parameters

|===
| Name | Type

| `view`
| xref:classes/ViewBase.adoc[`ViewBase`]

| `id`
| `string`
|===

==== Returns

xref:classes/ViewBase.adoc[`ViewBase`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/view-base/index.ts#L121[ui/core/view-base/index.ts:121]

'''

[#login]
=== login

▸ *login*(`message`, `userNameHint?`, `passwordHint?`, `userName?`, `password?`): `Promise`<xref:interfaces/LoginResult.adoc[`LoginResult`]>

The login() method displays a login dialog box that prompts the visitor for user name and password.

==== Parameters

|===
| Name | Type | Description

| `message`
| `string`
| The text to display in the dialog box.

| `userNameHint?`
| `string`
| The default text to display as a hint in the username input.
Optional.

| `passwordHint?`
| `string`
| The default text to display as a hint in the password input.
Optional.

| `userName?`
| `string`
| The default text to display in the user name input box.
Optional.

| `password?`
| `string`
| The default text to display in the password input box.
Optional.
|===

==== Returns

`Promise`<xref:interfaces/LoginResult.adoc[`LoginResult`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L107[ui/dialogs/index.d.ts:107]

▸ *login*(`message`, `userNameHint?`, `passwordHint?`): `Promise`<xref:interfaces/LoginResult.adoc[`LoginResult`]>

The login() method displays a login dialog box that prompts the visitor for user name and password.

==== Parameters

|===
| Name | Type | Description

| `message`
| `string`
| The text to display in the dialog box.

| `userNameHint?`
| `string`
| The default text to display as a hint in the username input.
Optional.

| `passwordHint?`
| `string`
| The default text to display as a hint in the password input.
Optional.
|===

==== Returns

`Promise`<xref:interfaces/LoginResult.adoc[`LoginResult`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L115[ui/dialogs/index.d.ts:115]

▸ *login*(`options`): `Promise`<xref:interfaces/LoginResult.adoc[`LoginResult`]>

The login() method displays a login dialog box that prompts the visitor for user name and password.

==== Parameters

|===
| Name | Type | Description

| `options`
| xref:interfaces/LoginOptions.adoc[`LoginOptions`]
| The options for the dialog box.
|===

==== Returns

`Promise`<xref:interfaces/LoginResult.adoc[`LoginResult`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L121[ui/dialogs/index.d.ts:121]

'''

[#makeparser]
=== makeParser

▸ *makeParser*<``T``>(`isValid`, `allowNumbers?`): (`value`: `any`) \=> `T`

==== Type parameters

|===
| Name

| `T`
|===

==== Parameters

|===
| Name | Type | Default value

| `isValid`
| (`value`: `any`) \=> `boolean`
| `undefined`

| `allowNumbers`
| `boolean`
| `false`
|===

==== Returns

`fn`

▸ (`value`): `T`

===== Parameters

|===
| Name | Type

| `value`
| `any`
|===

===== Returns

`T`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/properties/index.ts#L1547[ui/core/properties/index.ts:1547]

'''

[#makevalidator]
=== makeValidator

▸ *makeValidator*<``T``>(...`values`): (`value`: `any`) \=> value is T

==== Type parameters

|===
| Name

| `T`
|===

==== Parameters

|===
| Name | Type

| `+...values+`
| `T`[]
|===

==== Returns

`fn`

▸ (`value`): value is T

===== Parameters

|===
| Name | Type

| `value`
| `any`
|===

===== Returns

value is T

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/properties/index.ts#L1541[ui/core/properties/index.ts:1541]

'''

[#parsecssshadow]
=== parseCSSShadow

▸ *parseCSSShadow*(`value`): `CSSShadow`

Parse a string into a CSSShadow Supports any valid css box/text shadow combination.

inspired by https://github.com/jxnblk/css-box-shadow/blob/master/index.js (MIT License)

==== Parameters

|===
| Name | Type

| `value`
| `string`
|===

==== Returns

`CSSShadow`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/css-shadow.ts#L37[ui/styling/css-shadow.ts:37]

'''

[#parsekeyframedeclarations]
=== parseKeyframeDeclarations

▸ *parseKeyframeDeclarations*(`unparsedKeyframeDeclarations`): xref:classes/KeyframeDeclaration.adoc[`KeyframeDeclaration`][]

==== Parameters

|===
| Name | Type

| `unparsedKeyframeDeclarations`
| xref:classes/KeyframeDeclaration.adoc[`KeyframeDeclaration`][]
|===

==== Returns

xref:classes/KeyframeDeclaration.adoc[`KeyframeDeclaration`][]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/css-animation-parser.ts#L125[ui/styling/css-animation-parser.ts:125]

'''

[#profile]
=== profile

▸ *profile*(`nameFnOrTarget?`, `fnOrKey?`, `descriptor?`, `attrs?`): `any`

==== Parameters

|===
| Name | Type

| `nameFnOrTarget?`
| `string` \| `Object` \| `Function`

| `fnOrKey?`
| `string` \| `symbol` \| `Function`

| `descriptor?`
| `PropertyDescriptor`

| `attrs?`
| `any`
|===

==== Returns

`any`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L247[profiling/index.ts:247]

'''

[#profilingdisable]
=== profilingDisable

▸ *profilingDisable*(): `void`

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L175[profiling/index.ts:175]

'''

[#profilingdumpprofiles]
=== profilingDumpProfiles

▸ *profilingDumpProfiles*(): `void`

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L287[profiling/index.ts:287]

'''

[#profilingenable]
=== profilingEnable

▸ *profilingEnable*(`mode?`): `void`

==== Parameters

|===
| Name | Type | Default value

| `mode`
| link:modules.md#instrumentationmode[`InstrumentationMode`]
| `'counters'`
|===

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L147[profiling/index.ts:147]

'''

[#profilingisrunning]
=== profilingIsRunning

▸ *profilingIsRunning*(`name`): `boolean`

==== Parameters

|===
| Name | Type

| `name`
| `string`
|===

==== Returns

`boolean`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L93[profiling/index.ts:93]

'''

[#profilingresetprofiles]
=== profilingResetProfiles

▸ *profilingResetProfiles*(): `void`

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L298[profiling/index.ts:298]

'''

[#profilingstart]
=== profilingStart

▸ *profilingStart*(`name`): `void`

==== Parameters

|===
| Name | Type

| `name`
| `string`
|===

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L36[profiling/index.ts:36]

'''

[#profilingstartcpu]
=== profilingStartCPU

▸ *profilingStartCPU*(`name`): `void`

==== Parameters

|===
| Name | Type

| `name`
| `string`
|===

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L311[profiling/index.ts:311]

'''

[#profilingstop]
=== profilingStop

▸ *profilingStop*(`name`): xref:interfaces/TimerInfo.adoc[`TimerInfo`]

==== Parameters

|===
| Name | Type

| `name`
| `string`
|===

==== Returns

xref:interfaces/TimerInfo.adoc[`TimerInfo`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L54[profiling/index.ts:54]

'''

[#profilingstopcpu]
=== profilingStopCPU

▸ *profilingStopCPU*(`name`): `void`

==== Parameters

|===
| Name | Type

| `name`
| `string`
|===

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L317[profiling/index.ts:317]

'''

[#profilinguptime]
=== profilingUptime

▸ *profilingUptime*(): `any`

==== Returns

`any`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/profiling/index.ts#L5[profiling/index.ts:5]

'''

[#prompt]
=== prompt

▸ *prompt*(`message`, `defaultText?`): `Promise`<xref:interfaces/PromptResult.adoc[`PromptResult`]>

The prompt() method displays a dialog box that prompts the visitor for input.

==== Parameters

|===
| Name | Type | Description

| `message`
| `string`
| The text to display in the dialog box.

| `defaultText?`
| `string`
| The default text to display in the input box.
Optional.
|===

==== Returns

`Promise`<xref:interfaces/PromptResult.adoc[`PromptResult`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L91[ui/dialogs/index.d.ts:91]

▸ *prompt*(`options`): `Promise`<xref:interfaces/PromptResult.adoc[`PromptResult`]>

The prompt() method displays a dialog box that prompts the visitor for input.

==== Parameters

|===
| Name | Type | Description

| `options`
| xref:interfaces/PromptOptions.adoc[`PromptOptions`]
| The options for the dialog box.
|===

==== Returns

`Promise`<xref:interfaces/PromptResult.adoc[`PromptResult`]>

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L97[ui/dialogs/index.d.ts:97]

'''

[#removetaggedadditionalcss]
=== removeTaggedAdditionalCSS

▸ *removeTaggedAdditionalCSS*(`tag`): `boolean`

==== Parameters

|===
| Name | Type

| `tag`
| `string` \| `number`
|===

==== Returns

`boolean`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-scope.ts#L299[ui/styling/style-scope.ts:299]

'''

[#removeweakeventlistener]
=== removeWeakEventListener

▸ *removeWeakEventListener*(`source`, `eventName`, `handler`, `target`): `void`

==== Parameters

|===
| Name | Type

| `source`
| xref:classes/Observable.adoc[`Observable`]

| `eventName`
| `string`

| `handler`
| (`eventData`: xref:interfaces/EventData.adoc[`EventData`]) \=> `void`

| `target`
| `any`
|===

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/weak-event-listener/index.ts#L107[ui/core/weak-event-listener/index.ts:107]

'''

[#resolvefilenamefromurl]
=== resolveFileNameFromUrl

▸ *resolveFileNameFromUrl*(`url`, `appDirectory`, `fileExists`, `importSource?`): `string`

==== Parameters

|===
| Name | Type

| `url`
| `string`

| `appDirectory`
| `string`

| `fileExists`
| (`name`: `string`) \=> `boolean`

| `importSource?`
| `string`
|===

==== Returns

`string`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-scope.ts#L867[ui/styling/style-scope.ts:867]

'''

[#sanitizemodulename]
=== sanitizeModuleName

▸ *sanitizeModuleName*(`moduleName`, `removeExtension?`): `string`

Helps sanitize a module name if it is prefixed with '~/', '~' or '/'

==== Parameters

|===
| Name | Type | Default value | Description

| `moduleName`
| `string`
| `undefined`
| the name

| `removeExtension`
| `boolean`
| `true`
| whether to remove extension
|===

==== Returns

`string`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/builder/module-name-sanitizer.ts#L6[ui/builder/module-name-sanitizer.ts:6]

'''

[#setactivitycallbacks]
=== setActivityCallbacks

▸ *setActivityCallbacks*(`activity`): `void`

==== Parameters

|===
| Name | Type

| `activity`
| `any`
|===

==== Returns

`void`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L510[ui/frame/index.d.ts:510]

'''

[#timeconverter]
=== timeConverter

▸ *timeConverter*(`value`): `number`

==== Parameters

|===
| Name | Type

| `value`
| `string`
|===

==== Returns

`number`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/converters.ts#L12[ui/styling/converters.ts:12]

'''

[#transformconverter]
=== transformConverter

▸ *transformConverter*(`text`): `TransformFunctionsInfo`

==== Parameters

|===
| Name | Type

| `text`
| `string`
|===

==== Returns

`TransformFunctionsInfo`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/styling/style-properties.ts#L692[ui/styling/style-properties.ts:692]
