:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / ActionOptions

= Interface: ActionOptions

Provides options for the dialog.

== Hierarchy

* xref:CancelableOptions.adoc[`CancelableOptions`]
+
↳ *`ActionOptions`*

== Table of contents

=== Properties

* link:ActionOptions.md#actions[actions]
* link:ActionOptions.md#cancelbuttontext[cancelButtonText]
* link:ActionOptions.md#cancelable[cancelable]
* link:ActionOptions.md#destructiveactionsindexes[destructiveActionsIndexes]
* link:ActionOptions.md#message[message]
* link:ActionOptions.md#theme[theme]
* link:ActionOptions.md#title[title]

== Properties

[#actions]
=== actions

• `Optional` *actions*: `string`[]

Gets or sets the list of available actions.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L174[ui/dialogs/index.d.ts:174]

'''

[#cancelbuttontext]
=== cancelButtonText

• `Optional` *cancelButtonText*: `string`

Gets or sets the Cancel button text.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L169[ui/dialogs/index.d.ts:169]

'''

[#cancelable]
=== cancelable

• `Optional` *cancelable*: `boolean`

[Android only] Gets or sets if the dialog can be canceled by taping outside of the dialog.

==== Inherited from

xref:CancelableOptions.adoc[CancelableOptions].link:CancelableOptions.md#cancelable[cancelable]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L144[ui/dialogs/index.d.ts:144]

'''

[#destructiveactionsindexes]
=== destructiveActionsIndexes

• `Optional` *destructiveActionsIndexes*: `number`[]

[iOS only] Gets or sets the indexes of destructive actions.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L179[ui/dialogs/index.d.ts:179]

'''

[#message]
=== message

• `Optional` *message*: `string`

Gets or sets the dialog message.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L164[ui/dialogs/index.d.ts:164]

'''

[#theme]
=== theme

• `Optional` *theme*: `number`

[Android only] Sets the theme of the Dialog.
Usable themes can be found: https://developer.android.com/reference/android/R.style

==== Inherited from

xref:CancelableOptions.adoc[CancelableOptions].link:CancelableOptions.md#theme[theme]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L149[ui/dialogs/index.d.ts:149]

'''

[#title]
=== title

• `Optional` *title*: `string`

Gets or sets the dialog title.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L159[ui/dialogs/index.d.ts:159]
