:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / AndroidActivityBackPressedEventData

= Interface: AndroidActivityBackPressedEventData

Data for the Android activity back pressed event.

== Hierarchy

* xref:AndroidActivityEventData.adoc[`AndroidActivityEventData`]
+
↳ *`AndroidActivityBackPressedEventData`*

== Table of contents

=== Properties

* link:AndroidActivityBackPressedEventData.md#activity[activity]
* link:AndroidActivityBackPressedEventData.md#cancel[cancel]
* link:AndroidActivityBackPressedEventData.md#eventname[eventName]
* link:AndroidActivityBackPressedEventData.md#object[object]

== Properties

[#activity]
=== activity

• *activity*: `any`

The activity.

==== Inherited from

xref:AndroidActivityEventData.adoc[AndroidActivityEventData].link:AndroidActivityEventData.md#activity[activity]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/application/index.d.ts#L407[application/index.d.ts:407]

'''

[#cancel]
=== cancel

• *cancel*: `boolean`

In the event handler, set this value to true if you want to cancel the back navigation and do something else instead.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/application/index.d.ts#L487[application/index.d.ts:487]

'''

[#eventname]
=== eventName

• *eventName*: `string`

The name of the event.

==== Inherited from

xref:AndroidActivityEventData.adoc[AndroidActivityEventData].link:AndroidActivityEventData.md#eventname[eventName]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/application/index.d.ts#L412[application/index.d.ts:412]

'''

[#object]
=== object

• *object*: `any`

The instance that has raised the event.

==== Inherited from

xref:AndroidActivityEventData.adoc[AndroidActivityEventData].link:AndroidActivityEventData.md#object[object]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/application/index.d.ts#L417[application/index.d.ts:417]
