:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / CreateViewEventData

= Interface: CreateViewEventData

== Hierarchy

* xref:EventData.adoc[`EventData`]
+
↳ *`CreateViewEventData`*

== Table of contents

=== Properties

* link:CreateViewEventData.md#context[context]
* link:CreateViewEventData.md#eventname[eventName]
* link:CreateViewEventData.md#object[object]
* link:CreateViewEventData.md#view[view]

== Properties

[#context]
=== context

• `Optional` *context*: `any`

An optional context for creating the view.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/placeholder/placeholder-common.ts#L12[ui/placeholder/placeholder-common.ts:12]

'''

[#eventname]
=== eventName

• *eventName*: `string`

==== Inherited from

xref:EventData.adoc[EventData].link:EventData.md#eventname[eventName]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/data/observable/index.ts#L4[data/observable/index.ts:4]

'''

[#object]
=== object

• *object*: `Partial`<xref:../classes/Observable.adoc[`Observable`]>

==== Inherited from

xref:EventData.adoc[EventData].link:EventData.md#object[object]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/data/observable/index.ts#L5[data/observable/index.ts:5]

'''

[#view]
=== view

• *view*: `any`

The native view that should be added to the visual tree.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/placeholder/placeholder-common.ts#L7[ui/placeholder/placeholder-common.ts:7]
