:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / DialogOptions

= Interface: DialogOptions

Provides options for the dialog.

== Hierarchy

* xref:CancelableOptions.adoc[`CancelableOptions`]
+
↳ *`DialogOptions`*
+
↳↳ xref:AlertOptions.adoc[`AlertOptions`]

== Table of contents

=== Properties

* link:DialogOptions.md#cancelable[cancelable]
* link:DialogOptions.md#message[message]
* link:DialogOptions.md#theme[theme]
* link:DialogOptions.md#title[title]

== Properties

[#cancelable]
=== cancelable

• `Optional` *cancelable*: `boolean`

[Android only] Gets or sets if the dialog can be canceled by taping outside of the dialog.

==== Inherited from

xref:CancelableOptions.adoc[CancelableOptions].link:CancelableOptions.md#cancelable[cancelable]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L144[ui/dialogs/index.d.ts:144]

'''

[#message]
=== message

• `Optional` *message*: `string`

Gets or sets the dialog message.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L194[ui/dialogs/index.d.ts:194]

'''

[#theme]
=== theme

• `Optional` *theme*: `number`

[Android only] Sets the theme of the Dialog.
Usable themes can be found: https://developer.android.com/reference/android/R.style

==== Inherited from

xref:CancelableOptions.adoc[CancelableOptions].link:CancelableOptions.md#theme[theme]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L149[ui/dialogs/index.d.ts:149]

'''

[#title]
=== title

• `Optional` *title*: `string`

Gets or sets the dialog title.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L189[ui/dialogs/index.d.ts:189]
