

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / EventData

= Interface: EventData

== Hierarchy

* *`EventData`*
+
↳ xref:ApplicationEventData.adoc[`ApplicationEventData`]
+
↳ xref:CssChangedEventData.adoc[`CssChangedEventData`]
+
↳ xref:LoadAppCSSEventData.adoc[`LoadAppCSSEventData`]
+
↳ xref:ChangedData.adoc[`ChangedData`]
+
↳ xref:PropertyChangeData.adoc[`PropertyChangeData`]
+
↳ xref:ItemsLoading.adoc[`ItemsLoading`]
+
↳ xref:ShownModallyData.adoc[`ShownModallyData`]
+
↳ xref:GestureEventData.adoc[`GestureEventData`]
+
↳ xref:DownloadError.adoc[`DownloadError`]
+
↳ xref:DownloadedData.adoc[`DownloadedData`]
+
↳ xref:ItemEventData.adoc[`ItemEventData`]
+
↳ xref:NavigatedData.adoc[`NavigatedData`]
+
↳ xref:CreateViewEventData.adoc[`CreateViewEventData`]
+
↳ xref:ScrollEventData.adoc[`ScrollEventData`]
+
↳ xref:LoadEventData.adoc[`LoadEventData`]

== Table of contents

=== Properties

* link:EventData.md#eventname[eventName]
* link:EventData.md#object[object]

== Properties

[#eventname]
=== eventName

• *eventName*: `string`

==== Defined in https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/data/observable/index.ts#L4[data/observable/index.ts:4]

'''

[#object]
=== object

• *object*: `Partial`<xref:../classes/Observable.adoc[`Observable`]>

==== Defined in https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/data/observable/index.ts#L5[data/observable/index.ts:5]
