:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / HttpRequestOptions

= Interface: HttpRequestOptions

Provides options for the http requests.

== Table of contents

=== Properties

* link:HttpRequestOptions.md#content[content]
* link:HttpRequestOptions.md#dontfollowredirects[dontFollowRedirects]
* link:HttpRequestOptions.md#headers[headers]
* link:HttpRequestOptions.md#method[method]
* link:HttpRequestOptions.md#timeout[timeout]
* link:HttpRequestOptions.md#url[url]

== Properties

[#content]
=== content

• `Optional` *content*: `string` | `FormData` | `ArrayBuffer`

Gets or sets the request body.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/http/index.ts#L28[http/index.ts:28]

'''

[#dontfollowredirects]
=== dontFollowRedirects

• `Optional` *dontFollowRedirects*: `boolean`

Gets or sets whether to _not_ follow server's redirection responses.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/http/index.ts#L38[http/index.ts:38]

'''

[#headers]
=== headers

• `Optional` *headers*: `any`

Gets or sets the request headers in JSON format.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/http/index.ts#L23[http/index.ts:23]

'''

[#method]
=== method

• *method*: `string`

Gets or sets the request method.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/http/index.ts#L18[http/index.ts:18]

'''

[#timeout]
=== timeout

• `Optional` *timeout*: `number`

Gets or sets the request timeout in milliseconds.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/http/index.ts#L33[http/index.ts:33]

'''

[#url]
=== url

• *url*: `string`

Gets or sets the request url.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/http/index.ts#L13[http/index.ts:13]
