:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / LaunchEventData

= Interface: LaunchEventData

Event data containing information for launch event.

== Hierarchy

* xref:ApplicationEventData.adoc[`ApplicationEventData`]
+
↳ *`LaunchEventData`*

== Table of contents

=== Properties

* link:LaunchEventData.md#android[android]
* link:LaunchEventData.md#eventname[eventName]
* link:LaunchEventData.md#ios[ios]
* link:LaunchEventData.md#object[object]
* link:LaunchEventData.md#root[root]
* link:LaunchEventData.md#savedinstancestate[savedInstanceState]

== Properties

[#android]
=== android

• `Optional` *android*: `any`

Gets the native Android event arguments.
Valid only when running on Android.

==== Inherited from

xref:ApplicationEventData.adoc[ApplicationEventData].link:ApplicationEventData.md#android[android]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/application/index.d.ts#L114[application/index.d.ts:114]

'''

[#eventname]
=== eventName

• *eventName*: `string`

The name of the event.

==== Inherited from

xref:ApplicationEventData.adoc[ApplicationEventData].link:ApplicationEventData.md#eventname[eventName]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/application/index.d.ts#L119[application/index.d.ts:119]

'''

[#ios]
=== ios

• `Optional` *ios*: `any`

Gets the native iOS event arguments.
Valid only when running on iOS.

==== Inherited from

xref:ApplicationEventData.adoc[ApplicationEventData].link:ApplicationEventData.md#ios[ios]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/application/index.d.ts#L109[application/index.d.ts:109]

'''

[#object]
=== object

• *object*: `any`

The instance that has raised the event.

==== Inherited from

xref:ApplicationEventData.adoc[ApplicationEventData].link:ApplicationEventData.md#object[object]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/application/index.d.ts#L124[application/index.d.ts:124]

'''

[#root]
=== root

• `Optional` *root*: xref:../classes/View.adoc[`View`]

The root view for this Window on iOS or Activity for Android.
If not set a new Frame will be created as a root view in order to maintain backwards compatibility.
If explicitly set to null, there will be no root view.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/application/index.d.ts#L136[application/index.d.ts:136]

'''

[#savedinstancestate]
=== savedInstanceState

• `Optional` *savedInstanceState*: `any`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/application/index.d.ts#L138[application/index.d.ts:138]
