:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / NavigationTransition

= Interface: NavigationTransition

Represents an object specifying a page navigation transition.

== Table of contents

=== Properties

* link:NavigationTransition.md#curve[curve]
* link:NavigationTransition.md#duration[duration]
* link:NavigationTransition.md#instance[instance]
* link:NavigationTransition.md#name[name]

== Properties

[#curve]
=== curve

• `Optional` *curve*: `any`

An optional transition animation curve.
Possible values are contained in the https://docs.nativescript.org/api-reference/modules/_ui_enums_.animationcurve.html[AnimationCurve enumeration].
Alternatively, you can pass an instance of type UIViewAnimationCurve for iOS or android.animation.TimeInterpolator for Android.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L378[ui/frame/index.d.ts:378]

'''

[#duration]
=== duration

• `Optional` *duration*: `number`

The length of the transition in milliseconds.
If you do not specify this, the default platform transition duration will be used.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L372[ui/frame/index.d.ts:372]

'''

[#instance]
=== instance

• `Optional` *instance*: xref:../classes/Transition.adoc[`Transition`]

An user-defined instance of the "ui/transition".Transition class.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L367[ui/frame/index.d.ts:367]

'''

[#name]
=== name

• `Optional` *name*: `string`

Can be one of the built-in transitions:

* curl (same as curlUp) (iOS only)
* curlUp (iOS only)
* curlDown (iOS only)
* explode (Android Lollipop(21) and up only)
* fade
* flip (same as flipRight)
* flipRight
* flipLeft
* slide (same as slideLeft)
* slideLeft
* slideRight
* slideTop
* slideBottom

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L362[ui/frame/index.d.ts:362]
