:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / NavigationEntry

= Interface: NavigationEntry

Represents an entry in passed to navigate method.

== Hierarchy

* xref:ViewEntry.adoc[`ViewEntry`]
+
↳ *`NavigationEntry`*

== Table of contents

=== Properties

* link:NavigationEntry.md#animated[animated]
* link:NavigationEntry.md#backstackvisible[backstackVisible]
* link:NavigationEntry.md#bindingcontext[bindingContext]
* link:NavigationEntry.md#clearhistory[clearHistory]
* link:NavigationEntry.md#context[context]
* link:NavigationEntry.md#create[create]
* link:NavigationEntry.md#modulename[moduleName]
* link:NavigationEntry.md#transition[transition]
* link:NavigationEntry.md#transitionandroid[transitionAndroid]
* link:NavigationEntry.md#transitionios[transitioniOS]

== Properties

[#animated]
=== animated

• `Optional` *animated*: `boolean`

True to navigate to the new Page using animated transitions, false otherwise.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L304[ui/frame/index.d.ts:304]

'''

[#backstackvisible]
=== backstackVisible

• `Optional` *backstackVisible*: `boolean`

True to record the navigation in the backstack, false otherwise.
If the parameter is set to false then the Page will be displayed but once navigated from it will not be able to be navigated back to.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L325[ui/frame/index.d.ts:325]

'''

[#bindingcontext]
=== bindingContext

• `Optional` *bindingContext*: `any`

An object to become the binding context of the page navigating to.
Optional.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L299[ui/frame/index.d.ts:299]

'''

[#clearhistory]
=== clearHistory

• `Optional` *clearHistory*: `boolean`

True to clear the navigation history, false otherwise.
Very useful when navigating away from login pages.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L330[ui/frame/index.d.ts:330]

'''

[#context]
=== context

• `Optional` *context*: `any`

An object passed to the onNavigatedTo callback of the Page.
Typically this is used to pass some data among pages.
Optional.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L294[ui/frame/index.d.ts:294]

'''

[#create]
=== create

• `Optional` *create*: () \=> xref:../classes/View.adoc[`View`]

==== Type declaration

▸ (): xref:../classes/View.adoc[`View`]

A function used to create the View instance.
Optional.

===== Returns

xref:../classes/View.adoc[`View`]

==== Inherited from

xref:ViewEntry.adoc[ViewEntry].link:ViewEntry.md#create[create]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L285[ui/frame/index.d.ts:285]

'''

[#modulename]
=== moduleName

• `Optional` *moduleName*: `string`

The name of the module containing the View instance to load.
Optional.

==== Inherited from

xref:ViewEntry.adoc[ViewEntry].link:ViewEntry.md#modulename[moduleName]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L280[ui/frame/index.d.ts:280]

'''

[#transition]
=== transition

• `Optional` *transition*: xref:NavigationTransition.adoc[`NavigationTransition`]

Specifies an optional navigation transition for all platforms.
If not specified, the default platform transition will be used.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L309[ui/frame/index.d.ts:309]

'''

[#transitionandroid]
=== transitionAndroid

• `Optional` *transitionAndroid*: xref:NavigationTransition.adoc[`NavigationTransition`]

Specifies an optional navigation transition for Android.
If not specified, the default platform transition will be used.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L319[ui/frame/index.d.ts:319]

'''

[#transitionios]
=== transitioniOS

• `Optional` *transitioniOS*: xref:NavigationTransition.adoc[`NavigationTransition`]

Specifies an optional navigation transition for iOS.
If not specified, the default platform transition will be used.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/frame/index.d.ts#L314[ui/frame/index.d.ts:314]
