:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / PromptOptions

= Interface: PromptOptions

Provides options for the prompt dialog.

== Hierarchy

* xref:ConfirmOptions.adoc[`ConfirmOptions`]
+
↳ *`PromptOptions`*

== Table of contents

=== Properties

* link:PromptOptions.md#cancelbuttontext[cancelButtonText]
* link:PromptOptions.md#cancelable[cancelable]
* link:PromptOptions.md#capitalizationtype[capitalizationType]
* link:PromptOptions.md#defaulttext[defaultText]
* link:PromptOptions.md#inputtype[inputType]
* link:PromptOptions.md#message[message]
* link:PromptOptions.md#neutralbuttontext[neutralButtonText]
* link:PromptOptions.md#okbuttontext[okButtonText]
* link:PromptOptions.md#theme[theme]
* link:PromptOptions.md#title[title]

== Properties

[#cancelbuttontext]
=== cancelButtonText

• `Optional` *cancelButtonText*: `string`

Gets or sets the Cancel button text.

==== Inherited from

xref:ConfirmOptions.adoc[ConfirmOptions].link:ConfirmOptions.md#cancelbuttontext[cancelButtonText]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L214[ui/dialogs/index.d.ts:214]

'''

[#cancelable]
=== cancelable

• `Optional` *cancelable*: `boolean`

[Android only] Gets or sets if the dialog can be canceled by taping outside of the dialog.

==== Inherited from

xref:ConfirmOptions.adoc[ConfirmOptions].link:ConfirmOptions.md#cancelable[cancelable]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L144[ui/dialogs/index.d.ts:144]

'''

[#capitalizationtype]
=== capitalizationType

• `Optional` *capitalizationType*: `string`

Gets or sets the prompt capitalizationType (none, all, sentences, or words).

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L239[ui/dialogs/index.d.ts:239]

'''

[#defaulttext]
=== defaultText

• `Optional` *defaultText*: `string`

Gets or sets the default text to display in the input box.

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L229[ui/dialogs/index.d.ts:229]

'''

[#inputtype]
=== inputType

• `Optional` *inputType*: `string`

Gets or sets the prompt input type (plain text, password, or email).

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L234[ui/dialogs/index.d.ts:234]

'''

[#message]
=== message

• `Optional` *message*: `string`

Gets or sets the dialog message.

==== Inherited from

xref:ConfirmOptions.adoc[ConfirmOptions].link:ConfirmOptions.md#message[message]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L194[ui/dialogs/index.d.ts:194]

'''

[#neutralbuttontext]
=== neutralButtonText

• `Optional` *neutralButtonText*: `string`

Gets or sets the neutral button text.

==== Inherited from

xref:ConfirmOptions.adoc[ConfirmOptions].link:ConfirmOptions.md#neutralbuttontext[neutralButtonText]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L219[ui/dialogs/index.d.ts:219]

'''

[#okbuttontext]
=== okButtonText

• `Optional` *okButtonText*: `string`

Gets or sets the OK button text.

==== Inherited from

xref:ConfirmOptions.adoc[ConfirmOptions].link:ConfirmOptions.md#okbuttontext[okButtonText]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L204[ui/dialogs/index.d.ts:204]

'''

[#theme]
=== theme

• `Optional` *theme*: `number`

[Android only] Sets the theme of the Dialog.
Usable themes can be found: https://developer.android.com/reference/android/R.style

==== Inherited from

xref:ConfirmOptions.adoc[ConfirmOptions].link:ConfirmOptions.md#theme[theme]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L149[ui/dialogs/index.d.ts:149]

'''

[#title]
=== title

• `Optional` *title*: `string`

Gets or sets the dialog title.

==== Inherited from

xref:ConfirmOptions.adoc[ConfirmOptions].link:ConfirmOptions.md#title[title]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/dialogs/index.d.ts#L189[ui/dialogs/index.d.ts:189]
