:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / SwipeGestureEventData

= Interface: SwipeGestureEventData

Provides gesture event data for swipe gesture.

== Hierarchy

* xref:GestureEventData.adoc[`GestureEventData`]
+
↳ *`SwipeGestureEventData`*

== Table of contents

=== Properties

* link:SwipeGestureEventData.md#android[android]
* link:SwipeGestureEventData.md#direction[direction]
* link:SwipeGestureEventData.md#eventname[eventName]
* link:SwipeGestureEventData.md#ios[ios]
* link:SwipeGestureEventData.md#object[object]
* link:SwipeGestureEventData.md#type[type]
* link:SwipeGestureEventData.md#view[view]

== Properties

[#android]
=== android

• *android*: `any`

Gets the underlying native android specific http://developer.android.com/reference/android/view/GestureDetector.html[gesture detector].

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#android[android]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L151[ui/gestures/index.d.ts:151]

'''

[#direction]
=== direction

• *direction*: xref:../enums/SwipeDirection.adoc[`SwipeDirection`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L262[ui/gestures/index.d.ts:262]

'''

[#eventname]
=== eventName

• *eventName*: `string`

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#eventname[eventName]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/data/observable/index.ts#L4[data/observable/index.ts:4]

'''

[#ios]
=== ios

• *ios*: `any`

Gets the underlying native iOS specific https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIGestureRecognizer_Class/[UIGestureRecognizer].

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#ios[ios]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L147[ui/gestures/index.d.ts:147]

'''

[#object]
=== object

• *object*: `Partial`<xref:../classes/Observable.adoc[`Observable`]>

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#object[object]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/data/observable/index.ts#L5[data/observable/index.ts:5]

'''

[#type]
=== type

• *type*: xref:../enums/GestureTypes.adoc[`GestureTypes`]

Gets the type of the gesture.

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#type[type]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L139[ui/gestures/index.d.ts:139]

'''

[#view]
=== view

• *view*: `Partial`<xref:../classes/View.adoc[`View`]>

Gets the view which originates the gesture.

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#view[view]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L143[ui/gestures/index.d.ts:143]
