:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / TapGestureEventData

= Interface: TapGestureEventData

Provides gesture event data.

== Hierarchy

* xref:GestureEventData.adoc[`GestureEventData`]
+
↳ *`TapGestureEventData`*
+
↳↳ xref:TouchGestureEventData.adoc[`TouchGestureEventData`]

== Table of contents

=== Properties

* link:TapGestureEventData.md#android[android]
* link:TapGestureEventData.md#eventname[eventName]
* link:TapGestureEventData.md#ios[ios]
* link:TapGestureEventData.md#object[object]
* link:TapGestureEventData.md#type[type]
* link:TapGestureEventData.md#view[view]

=== Methods

* link:TapGestureEventData.md#getpointercount[getPointerCount]
* link:TapGestureEventData.md#getx[getX]
* link:TapGestureEventData.md#gety[getY]

== Properties

[#android]
=== android

• *android*: `any`

Gets the underlying native android specific http://developer.android.com/reference/android/view/GestureDetector.html[gesture detector].

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#android[android]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L151[ui/gestures/index.d.ts:151]

'''

[#eventname]
=== eventName

• *eventName*: `string`

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#eventname[eventName]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/data/observable/index.ts#L4[data/observable/index.ts:4]

'''

[#ios]
=== ios

• *ios*: `any`

Gets the underlying native iOS specific https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIGestureRecognizer_Class/[UIGestureRecognizer].

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#ios[ios]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L147[ui/gestures/index.d.ts:147]

'''

[#object]
=== object

• *object*: `Partial`<xref:../classes/Observable.adoc[`Observable`]>

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#object[object]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/data/observable/index.ts#L5[data/observable/index.ts:5]

'''

[#type]
=== type

• *type*: xref:../enums/GestureTypes.adoc[`GestureTypes`]

Gets the type of the gesture.

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#type[type]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L139[ui/gestures/index.d.ts:139]

'''

[#view]
=== view

• *view*: `Partial`<xref:../classes/View.adoc[`View`]>

Gets the view which originates the gesture.

==== Inherited from

xref:GestureEventData.adoc[GestureEventData].link:GestureEventData.md#view[view]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L143[ui/gestures/index.d.ts:143]

== Methods

[#getpointercount]
=== getPointerCount

▸ *getPointerCount*(): `number`

Gets the number of pointers in the event.

==== Returns

`number`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L161[ui/gestures/index.d.ts:161]

'''

[#getx]
=== getX

▸ *getX*(): `number`

Gets the X coordinate of this event inside the view that triggered the event

==== Returns

`number`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L165[ui/gestures/index.d.ts:165]

'''

[#gety]
=== getY

▸ *getY*(): `number`

Gets the Y coordinate of the event inside the view that triggered the event.

==== Returns

`number`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/gestures/index.d.ts#L169[ui/gestures/index.d.ts:169]
