= Progress

`<Progress>` is a UI component that shows a bar to indicate the progress of a task.

See also: xref:components::activityindicator.adoc[ActivityIndicator]

'''

== Example

=== Example: Simple Progress

[tabs]
====
Angular::
+
[tabs]
=====
HTML::
+
[,html]
----
<progress value="25" maxValue="100" (valueChanged)="onValueChanged($event)"></progress>
----

TypeScript::
+
[,ts]
----
import { Component, OnInit } from '@angular/core'

@Component({
  moduleId: module.id,
  templateUrl: './styling.component.html',
  styleUrls: ['./styling.component.css']
})
export class StylingComponent implements OnInit {
  public progressValue: number

  ngOnInit() {
    this.progressValue = 25
  }
}
----
=====

Plain::
+
[tabs]
=====
XML::
+
[,xml]
----
<Progress
  width="100%"
  value="{{ progressValue }}"
  maxValue="{{ progressMaxValue }}"
  loaded="onProgressLoaded"
/>
----

TypeScript::
+
[,ts]
----
import { Observable, Page, Progress, PropertyChangeData } from '@nativescript/core'

export function onNavigatingTo(args) {
  const page = args.object as Page
  const vm = new Observable()
  vm.set('progressValue', 10) // Initial value
  vm.set('progressMaxValue', 100) // Maximum value
  // Forcing progress value change (for demonstration)
  setInterval(() => {
    const value = vm.get('progressValue')
    vm.set('progressValue', value + 2)
  }, 300)
  page.bindingContext = vm
}
export function onProgressLoaded(args) {
  const myProgressBar = args.object as Progress
  myProgressBar.on('valueChange', (pargs: PropertyChangeData) => {
    // TIP: args (for valueChange of Progress) is extending EventData with oldValue & value parameters
    console.log(`Old Value: ${pargs.oldValue}`)
    console.log(`New Value: ${pargs.value}`)
  })
}
----
=====

React::
+
[,js]
----
function getTaskCompletionPercent() {
  // Just a stub method to illustrate the concept.
  return 10
}

;<progress value={getTaskCompletionPercent()} maxValue={100} />
----

Vue::
+
[,html]
----
<progress :value="currentProgress" />
----

Svelte::
+
[,html]
----
<progress value="{currentProgress}" />
----
====

=== Example: Styling Progress

Using `backgroundColor` (*CSS*: `background-color`) & color to change the Progress style.

[NOTE]
====
`backgroundColor` will work only on `iOS`;
on `Android` the background will be the color with applied opacity.
====

[tabs]
=====
HTML::
+
[,html]
----
<progress value="50" maxValue="100" backgroundColor="red" color="green"></progress>
<!-- Using the @nativescript/theme CSS class to change the Progress style -->
<progress value="25" maxValue="100" class="progress"></progress>
----

CSS::
+
[,css]
----
Progress {
  color: cyan;
  background-color: green;
}
----
=====

== Props

|===
| Name | Type | Description

| `value`
| `Number`
| Gets or sets the current value of the progress bar.
Must be within the range of 0 to `maxValue`.

| `maxValue`
| `Number`
| Gets or sets the maximum value of the progress bar.
+ Default value: `100`.

| `+...Inherited+`
| `Inherited`
| Additional inherited properties not shown.
Refer to the https://docs.nativescript.org/api-reference/classes/progress[API Reference]
|===

== Events

|===
| Name | Description

| `valueChange`
| Emitted when the `value` property changes.
|===

== Native Component

|===
| Android | iOS

| https://developer.android.com/reference/android/widget/ProgressBar.html[`android.widget.ProgressBar` (indeterminate = false)]
| https://developer.apple.com/documentation/uikit/uiprogressview[`UIProgressView`]
|===
