= Slider

`<Slider>` is a UI component that provides a slider control for picking values within a specified numeric range.

'''

== Examples

=== Example: Simple Slider

[tabs]
====
Angular::
+
[tabs]
=====
HTML::
+
[,html]
----
<Slider
  value="10"
  minValue="0"
  maxValue="100"
  (valueChange)="onSliderValueChange($event)"
>
</Slider>
----

TypeScript::
+
[,ts]
----
import { Component } from '@angular/core'
import { Slider } from '@nativescript/core'

@Component({
  moduleId: module.id,
  templateUrl: './usage.component.html'
})
export class UsageComponent {
  onSliderValueChange(args) {
    const slider = args.object as Slider
    console.log(`Slider new value ${args.value}`)
  }
}
----
=====

Plain::
+
[tabs]
=====
XML::
+
[,xml]
----
<Slider value="10" minValue="0" maxValue="100" loaded="onSliderLoaded" />
----

TS::
+
[,ts]
----
import { Slider } from '@nativescript/core'

export function onSliderLoaded(args) {
  const sliderComponent = args.object as Slider
  sliderComponent.on('valueChange', data => {
    console.log(`Slider new value ${data.value}`)
  })
}
----
=====

React::
+
[,tsx]
----
<slider value={0} onValueChange={onValueChange} />
----

Svelte::
+
[,tsx]
----
<slider value="80" on:valueChange="{onValueChanged}" />
----
+
`<slider>` provides two-way data binding of `value`:
+
[,html]
----
<slider bind:value="{value}" />
----

Vue::
+
[,html]
----
<Slider value="80" @valueChange="onValueChanged" />
----
+
`<Slider>` provides two-way data binding using `v-model`:
+
[,html]
----
<Slider v-model="value" />
----
====

== Props

|===
| Name | Type | Description

| `value`
| `Number`
| Gets or sets the currently selected value of the slider.
+ Default value: `0`.

| `minValue`
| `Number`
| Gets or sets the minimum value of the slider.
+ Default value: `0`.

| `maxValue`
| `Number`
| Gets or sets the maximum value of the slider.
+ Default value: `100`.

| `+...Inherited+`
| `Inherited`
| Additional inherited properties are not shown.
Refer to the https://docs.nativescript.org/api-reference/classes/slider[API Reference]
|===

// TODO: fix API links

== Events

|===
| Name | Description

| `valueChange`
| Emitted when the value of the slider changes.
|===

== Native component

|===
| Android | iOS

| https://developer.android.com/reference/android/widget/SeekBar.html[`android.widget.SeekBar`]
| https://developer.apple.com/documentation/uikit/uislider[`UISlider`]
|===
