= TimePicker

`<TimePicker>` is a UI component that lets users select time.

See also: xref:components::datepicker.adoc[DatePicker].

'''

[tabs]
====
Angular::
+
[tabs]
=====
HTML::
+
[,html]
----
<TimePicker
  hour="9"
  minute="25"
  maxHour="23"
  maxMinute="59"
  minuteInterval="5"
  (timeChange)="onTimeChanged($event)"
>
</TimePicker>
----

TS::
+
[,ts]
----
import { Component } from '@angular/core'
import { TimePicker } from '@nativescript/core'

@Component({
  moduleId: module.id,
  templateUrl: './usage.component.html'
})
export class UsageComponent {
  todayObj: Date = new Date()

  onTimeChanged(args) {
    const tp = args.object as TimePicker

    const time = args.value
    console.log(`Chosen time: ${time}`)
  }
}
----
=====
[tabs]
=====
Plain::
+
[tabs]
======
XML::
+
[,xml]
----
<TimePicker
  hour="10"
  minute="25"
  loaded="onPickerLoaded"
  row="2"
  col="0"
  colSpan="2"
  class="m-15"
  verticalAlignment="center"
/>
----

TS::
+
[,js]
----
import { TimePicker } from '@nativescript/core'

export function onPickerLoaded(args) {
  const timePicker = args.object as TimePicker

  // Configurable properties of TimePicker
  timePicker.hour = 10
  timePicker.minute = 25
  timePicker.minuteInterval = 5
  timePicker.minHour = 7
  timePicker.maxHour = 11
  timePicker.minMinute = 10
  timePicker.maxMinute = 45
  timePicker.time = new Date()

  // handling 'timeChange' event via code behind
  timePicker.on('timeChange', (data: any) => {
    // data is of type PropertyChangeData
    console.log('Picked TIME: ', data.value)
    console.log('Previous TIME: ', data.oldValue)
  })
}
----
======
=====
React::
+
[,js]
----
<timePicker hour={selectedHour} minute={selectedMinute} />
----

Vue::
+

[,html]
----
<TimePicker :hour="selectedHour" :minute="selectedMinute" />
----
+
`<TimePicker>` provides two-way data binding using `v-model`.
+
[,html]
----
<TimePicker v-model="selectedTime" />
----

Svelte::
+
[,tsx]
----
<timePicker hour="{selectedHour}" minute="{selectedMinute}" />
----
+
`<timePicker>` provides two-way data binding using `bind`.
+
[,html]
----
<timePicker bind:time="{selectedTime}" />
----
====

== Props

|===
| Name | Type | Description

| `hour`
| `Number`
| Gets or sets the selected hour.

| `minute`
| `Number`
| Gets or sets the selected minute.

| `time`
| `Date`
| Gets or sets the selected time.

| `minHour`
| `Number`
| Gets or sets the minimum selectable hour.

| `maxHour`
| `Number`
| Gets or sets the maximum selectable hour.

| `minMinute`
| `Number`
| Gets or sets the minimum selectable minute.

| `maxMinute`
| `Number`
| Gets or sets the maximum selectable minute.

| `minuteInterval`
| `Number`
| Gets or sets the selectable minute interval.
For example: 5 or 15 minutes.
+ Default value: `1`.

| `+...Inherited+`
| `Inherited`
| Additional inherited properties are not shown.
Refer to the https://docs.nativescript.org/api-reference/classes/timepicker[API Reference]
|===

//TODO: Fix API Links

== Events

|===
| Name | Description

| `timeChange`
| Emitted when the selected time changes.
|===

== Native component

|===
| Android | iOS

| https://developer.android.com/reference/android/widget/TimePicker[`android.widget.TimePicker`]
| https://developer.apple.com/documentation/uikit/uidatepicker[`UIDatePicker`]
|===
