= Plugins

== @nativescript/* plugins

Many plugins offered by NativeScript's Technical Steering Committee (TSC) are listed in the sidebar/sub navigation to help with your developments. For example, everything from https://docs.nativescript.org/plugins/biometrics.html[biometrics], https://docs.nativescript.org/plugins/camera.html[camera] handling, https://docs.nativescript.org/plugins/contacts.html[contacts] management, https://docs.nativescript.org/plugins/firebase-core.html[Firebase] integration, https://docs.nativescript.org/plugins/google-maps.html[Google Maps], to payment management using https://docs.nativescript.org/plugins/apple-pay.html[Apple Pay], https://docs.nativescript.org/plugins/google-pay.html[Google Pay], or https://docs.nativescript.org/plugins/payments.html[IAP and Subscription handling] and many more can be found here.

== Developing your own plugins

If you are interested in building your own plugins, we recommend following our https://docs.nativescript.org/plugins/plugin-workspace-guide.html[Getting Started with Plugin Workspaces] guide which uses our https://github.com/NativeScript/plugin-seed[plugin workspace seed] (_the exact same setup the TSC uses to develop it's own plugins_) as a starting point because it provides the following:

* consistent plugin source structure
* ability to scale and add additional plugins through automated tooling
* reduces configuration files to provide easy maintainence
* provides shareable structure for ease of demoing your plugins
* ability to focus your workspace down to a single plugin in an instant if you ever need to isolate development when working within a multi-plugin workspace
* provides automated migrations managed by the TSC to keep your plugin workspaces up-to-date without manual hassles

You may also find these resources helpful:

* https://blog.nativescript.org/announcing-plugin-workspaces[Introducing plugin workspaces to simplify and streamline maintenance]
* https://blog.nativescript.org/plugin-workspace-migrate-to-v2[Migrate your plugin workspace in 2 seconds - NativeScript 8 + webpack5 + configuration updates]

=== Creating NativeScript Plugins and Enhancing Behavior

* https://blog.nativescript.org/create-a-custom-view-plugin-marquee-label[Part 1: How to create a NativeScript plugin that uses native iOS & Android views - Label Marquee!]
* https://blog.nativescript.org/create-a-custom-view-plugin-shimmer[Part 2: How to create a NativeScript plugin that uses native iOS & Android views - more native platform APIs - Shimmer!]
* https://blog.nativescript.org/create-a-custom-view-plugin-touch-effects[Part 3: Should this be a plugin or part of core? 💥 Holy Interactivity Batman!]
