

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / xref:CoreTypes.adoc[CoreTypes] / Visibility

= Namespace: Visibility

xref:CoreTypes.adoc[CoreTypes].Visibility

== Table of contents

=== Variables

* link:CoreTypes.Visibility.md#collapse[collapse]
* link:CoreTypes.Visibility.md#collapsed[collapsed]
* link:CoreTypes.Visibility.md#hidden[hidden]
* link:CoreTypes.Visibility.md#visible[visible]

=== Functions

* link:CoreTypes.Visibility.md#isvalid[isValid]
* link:CoreTypes.Visibility.md#parse[parse]

== Variables

[#collapse]
=== collapse

• `Const` *collapse*: link:CoreTypes.md#visibilitytype[`VisibilityType`] = `'collapse'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L148[core-types/index.ts:148]

'''

[#collapsed]
=== collapsed

• `Const` *collapsed*: link:CoreTypes.md#visibilitytype[`VisibilityType`] = `'collapsed'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L149[core-types/index.ts:149]

'''

[#hidden]
=== hidden

• `Const` *hidden*: link:CoreTypes.md#visibilitytype[`VisibilityType`] = `'hidden'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L150[core-types/index.ts:150]

'''

[#visible]
=== visible

• `Const` *visible*: link:CoreTypes.md#visibilitytype[`VisibilityType`] = `'visible'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L147[core-types/index.ts:147]

== Functions

[#isvalid]
=== isValid

▸ *isValid*(`value`): value is VisibilityType

==== Parameters

|===
| Name | Type

| `value`
| `any`
|===

==== Returns

value is VisibilityType

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/ui/core/properties/index.ts#L1541[ui/core/properties/index.ts:1541]

'''

[#parse]
=== parse

▸ *parse*(`value`): link:CoreTypes.md#visibilitytype[`VisibilityType`]

==== Parameters

|===
| Name | Type

| `value`
| `string`
|===

==== Returns

link:CoreTypes.md#visibilitytype[`VisibilityType`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L152[core-types/index.ts:152]
