:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / xref:CoreTypes.adoc[CoreTypes] / FontWeight

= Namespace: FontWeight

xref:CoreTypes.adoc[CoreTypes].FontWeight

== Table of contents

=== Variables

* link:CoreTypes.FontWeight.md#black[black]
* link:CoreTypes.FontWeight.md#bold[bold]
* link:CoreTypes.FontWeight.md#extrabold[extraBold]
* link:CoreTypes.FontWeight.md#extralight[extraLight]
* link:CoreTypes.FontWeight.md#light[light]
* link:CoreTypes.FontWeight.md#medium[medium]
* link:CoreTypes.FontWeight.md#normal[normal]
* link:CoreTypes.FontWeight.md#semibold[semiBold]
* link:CoreTypes.FontWeight.md#thin[thin]

== Variables

[#black]
=== black

• `Const` *black*: `string` = `'900'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L237[core-types/index.ts:237]

'''

[#bold]
=== bold

• `Const` *bold*: `string` = `'bold'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L235[core-types/index.ts:235]

'''

[#extrabold]
=== extraBold

• `Const` *extraBold*: `string` = `'800'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L236[core-types/index.ts:236]

'''

[#extralight]
=== extraLight

• `Const` *extraLight*: `string` = `'200'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L230[core-types/index.ts:230]

'''

[#light]
=== light

• `Const` *light*: `string` = `'300'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L231[core-types/index.ts:231]

'''

[#medium]
=== medium

• `Const` *medium*: `string` = `'500'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L233[core-types/index.ts:233]

'''

[#normal]
=== normal

• `Const` *normal*: `string` = `'normal'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L232[core-types/index.ts:232]

'''

[#semibold]
=== semiBold

• `Const` *semiBold*: `string` = `'600'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L234[core-types/index.ts:234]

'''

[#thin]
=== thin

• `Const` *thin*: `string` = `'100'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L229[core-types/index.ts:229]
