

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / xref:CoreTypes.adoc[CoreTypes] / AnimationCurve

= Namespace: AnimationCurve

xref:CoreTypes.adoc[CoreTypes].AnimationCurve

== Table of contents

=== Variables

* link:CoreTypes.AnimationCurve.md#ease[ease]
* link:CoreTypes.AnimationCurve.md#easein[easeIn]
* link:CoreTypes.AnimationCurve.md#easeinout[easeInOut]
* link:CoreTypes.AnimationCurve.md#easeout[easeOut]
* link:CoreTypes.AnimationCurve.md#linear[linear]
* link:CoreTypes.AnimationCurve.md#spring[spring]

=== Functions

* link:CoreTypes.AnimationCurve.md#cubicbezier[cubicBezier]

== Variables

[#ease]
=== ease

• `Const` *ease*: `"ease"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L253[core-types/index.ts:253]

'''

[#easein]
=== easeIn

• `Const` *easeIn*: `"easeIn"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L254[core-types/index.ts:254]

'''

[#easeinout]
=== easeInOut

• `Const` *easeInOut*: `"easeInOut"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L256[core-types/index.ts:256]

'''

[#easeout]
=== easeOut

• `Const` *easeOut*: `"easeOut"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L255[core-types/index.ts:255]

'''

[#linear]
=== linear

• `Const` *linear*: `"linear"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L257[core-types/index.ts:257]

'''

[#spring]
=== spring

• `Const` *spring*: `"spring"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L258[core-types/index.ts:258]

== Functions

[#cubicbezier]
=== cubicBezier

▸ *cubicBezier*(`x1`, `y1`, `x2`, `y2`): `Object`

==== Parameters

|===
| Name | Type

| `x1`
| `number`

| `y1`
| `number`

| `x2`
| `number`

| `y2`
| `number`
|===

==== Returns

`Object`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L259[core-types/index.ts:259]
