

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / xref:CoreTypes.adoc[CoreTypes] / ImageStretch

= Namespace: ImageStretch

xref:CoreTypes.adoc[CoreTypes].ImageStretch

== Table of contents

=== Variables

* link:CoreTypes.ImageStretch.md#aspectfill[aspectFill]
* link:CoreTypes.ImageStretch.md#aspectfit[aspectFit]
* link:CoreTypes.ImageStretch.md#fill[fill]
* link:CoreTypes.ImageStretch.md#none[none]

== Variables

[#aspectfill]
=== aspectFill

• `Const` *aspectFill*: link:CoreTypes.md#imagestretchtype[`ImageStretchType`] = `'aspectFill'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L140[core-types/index.ts:140]

'''

[#aspectfit]
=== aspectFit

• `Const` *aspectFit*: link:CoreTypes.md#imagestretchtype[`ImageStretchType`] = `'aspectFit'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L141[core-types/index.ts:141]

'''

[#fill]
=== fill

• `Const` *fill*: link:CoreTypes.md#imagestretchtype[`ImageStretchType`] = `'fill'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L142[core-types/index.ts:142]

'''

[#none]
=== none

• `Const` *none*: link:CoreTypes.md#imagestretchtype[`ImageStretchType`] = `'none'`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/core-types/index.ts#L139[core-types/index.ts:139]
