:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / CSSUtils

= Namespace: CSSUtils

== Table of contents

=== Variables

* link:CSSUtils.md#class_prefix[CLASS_PREFIX]
* link:CSSUtils.md#modal_root_view_css_class[MODAL_ROOT_VIEW_CSS_CLASS]
* link:CSSUtils.md#root_view_css_class[ROOT_VIEW_CSS_CLASS]

=== Functions

* link:CSSUtils.md#getmodalrootviewcssclass[getModalRootViewCssClass]
* link:CSSUtils.md#getrootviewcssclasses[getRootViewCssClasses]
* link:CSSUtils.md#getsystemcssclasses[getSystemCssClasses]
* link:CSSUtils.md#pushtorootviewcssclasses[pushToRootViewCssClasses]
* link:CSSUtils.md#pushtosystemcssclasses[pushToSystemCssClasses]
* link:CSSUtils.md#removefromrootviewcssclasses[removeFromRootViewCssClasses]
* link:CSSUtils.md#removesystemcssclass[removeSystemCssClass]

== Variables

[#class_prefix]
=== CLASS_PREFIX

• `Const` *CLASS_PREFIX*: `"ns-"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/css/system-classes.ts#L6[css/system-classes.ts:6]

'''

[#modal_root_view_css_class]
=== MODAL_ROOT_VIEW_CSS_CLASS

• `Const` *MODAL_ROOT_VIEW_CSS_CLASS*: `string`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/css/system-classes.ts#L7[css/system-classes.ts:7]

'''

[#root_view_css_class]
=== ROOT_VIEW_CSS_CLASS

• `Const` *ROOT_VIEW_CSS_CLASS*: `string`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/css/system-classes.ts#L8[css/system-classes.ts:8]

== Functions

[#getmodalrootviewcssclass]
=== getModalRootViewCssClass

▸ *getModalRootViewCssClass*(): `string`

==== Returns

`string`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/css/system-classes.ts#L31[css/system-classes.ts:31]

'''

[#getrootviewcssclasses]
=== getRootViewCssClasses

▸ *getRootViewCssClasses*(): `string`[]

==== Returns

`string`[]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/css/system-classes.ts#L35[css/system-classes.ts:35]

'''

[#getsystemcssclasses]
=== getSystemCssClasses

▸ *getSystemCssClasses*(): `string`[]

==== Returns

`string`[]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/css/system-classes.ts#L10[css/system-classes.ts:10]

'''

[#pushtorootviewcssclasses]
=== pushToRootViewCssClasses

▸ *pushToRootViewCssClasses*(`value`): `number`

==== Parameters

|===
| Name | Type

| `value`
| `string`
|===

==== Returns

`number`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/css/system-classes.ts#L39[css/system-classes.ts:39]

'''

[#pushtosystemcssclasses]
=== pushToSystemCssClasses

▸ *pushToSystemCssClasses*(`value`): `number`

==== Parameters

|===
| Name | Type

| `value`
| `string`
|===

==== Returns

`number`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/css/system-classes.ts#L14[css/system-classes.ts:14]

'''

[#removefromrootviewcssclasses]
=== removeFromRootViewCssClasses

▸ *removeFromRootViewCssClasses*(`value`): `string`

==== Parameters

|===
| Name | Type

| `value`
| `string`
|===

==== Returns

`string`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/css/system-classes.ts#L43[css/system-classes.ts:43]

'''

[#removesystemcssclass]
=== removeSystemCssClass

▸ *removeSystemCssClass*(`value`): `string`

==== Parameters

|===
| Name | Type

| `value`
| `string`
|===

==== Returns

`string`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/css/system-classes.ts#L20[css/system-classes.ts:20]
