:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / knownFolders

= Namespace: knownFolders

== Table of contents

=== Namespaces

* xref:knownFolders.ios.adoc[ios]

=== Functions

* link:knownFolders.md#currentapp[currentApp]
* link:knownFolders.md#documents[documents]
* link:knownFolders.md#externaldocuments[externalDocuments]
* link:knownFolders.md#temp[temp]

== Functions

[#currentapp]
=== currentApp

▸ *currentApp*(): xref:../classes/Folder.adoc[`Folder`]

==== Returns

xref:../classes/Folder.adoc[`Folder`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/file-system/index.ts#L588[file-system/index.ts:588]

'''

[#documents]
=== documents

▸ *documents*(): xref:../classes/Folder.adoc[`Folder`]

==== Returns

xref:../classes/Folder.adoc[`Folder`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/file-system/index.ts#L555[file-system/index.ts:555]

'''

[#externaldocuments]
=== externalDocuments

▸ *externalDocuments*(): xref:../classes/Folder.adoc[`Folder`]

==== Returns

xref:../classes/Folder.adoc[`Folder`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/file-system/index.ts#L566[file-system/index.ts:566]

'''

[#temp]
=== temp

▸ *temp*(): xref:../classes/Folder.adoc[`Folder`]

==== Returns

xref:../classes/Folder.adoc[`Folder`]

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/file-system/index.ts#L577[file-system/index.ts:577]
