:doctype: book

xref:../README.adoc[NativeScript] / xref:../modules.adoc[Exports] / xref:Trace.adoc[Trace] / categories

= Namespace: categories

xref:Trace.adoc[Trace].categories

all predefined categories.

== Table of contents

=== Variables

* link:Trace.categories.md#accessibility[Accessibility]
* link:Trace.categories.md#all[All]
* link:Trace.categories.md#animation[Animation]
* link:Trace.categories.md#binding[Binding]
* link:Trace.categories.md#bindingerror[BindingError]
* link:Trace.categories.md#debug[Debug]
* link:Trace.categories.md#error[Error]
* link:Trace.categories.md#layout[Layout]
* link:Trace.categories.md#livesync[Livesync]
* link:Trace.categories.md#modulenameresolver[ModuleNameResolver]
* link:Trace.categories.md#nativelifecycle[NativeLifecycle]
* link:Trace.categories.md#navigation[Navigation]
* link:Trace.categories.md#style[Style]
* link:Trace.categories.md#test[Test]
* link:Trace.categories.md#transition[Transition]
* link:Trace.categories.md#viewhierarchy[ViewHierarchy]
* link:Trace.categories.md#visualtreeevents[VisualTreeEvents]
* link:Trace.categories.md#separator[separator]

=== Functions

* link:Trace.categories.md#concat[concat]

== Variables

[#accessibility]
=== Accessibility

• `Const` *Accessibility*: `"Accessibility"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L188[trace/index.ts:188]

'''

[#all]
=== All

• `Const` *All*: `string`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L206[trace/index.ts:206]

'''

[#animation]
=== Animation

• `Const` *Animation*: `"Animation"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L200[trace/index.ts:200]

'''

[#binding]
=== Binding

• `Const` *Binding*: `"Binding"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L197[trace/index.ts:197]

'''

[#bindingerror]
=== BindingError

• `Const` *BindingError*: `"BindingError"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L198[trace/index.ts:198]

'''

[#debug]
=== Debug

• `Const` *Debug*: `"Debug"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L194[trace/index.ts:194]

'''

[#error]
=== Error

• `Const` *Error*: `"Error"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L199[trace/index.ts:199]

'''

[#layout]
=== Layout

• `Const` *Layout*: `"Layout"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L190[trace/index.ts:190]

'''

[#livesync]
=== Livesync

• `Const` *Livesync*: `"Livesync"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L202[trace/index.ts:202]

'''

[#modulenameresolver]
=== ModuleNameResolver

• `Const` *ModuleNameResolver*: `"ModuleNameResolver"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L203[trace/index.ts:203]

'''

[#nativelifecycle]
=== NativeLifecycle

• `Const` *NativeLifecycle*: `"NativeLifecycle"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L193[trace/index.ts:193]

'''

[#navigation]
=== Navigation

• `Const` *Navigation*: `"Navigation"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L195[trace/index.ts:195]

'''

[#style]
=== Style

• `Const` *Style*: `"Style"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L191[trace/index.ts:191]

'''

[#test]
=== Test

• `Const` *Test*: `"Test"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L196[trace/index.ts:196]

'''

[#transition]
=== Transition

• `Const` *Transition*: `"Transition"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L201[trace/index.ts:201]

'''

[#viewhierarchy]
=== ViewHierarchy

• `Const` *ViewHierarchy*: `"ViewHierarchy"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L192[trace/index.ts:192]

'''

[#visualtreeevents]
=== VisualTreeEvents

• `Const` *VisualTreeEvents*: `"VisualTreeEvents"`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L189[trace/index.ts:189]

'''

[#separator]
=== separator

• `Const` *separator*: `","`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L205[trace/index.ts:205]

== Functions

[#concat]
=== concat

▸ *concat*(...`args`): `string`

==== Parameters

|===
| Name | Type

| `+...args+`
| `any`
|===

==== Returns

`string`

==== Defined in

https://github.com/NativeScript/NativeScript/blob/02d4834bd/packages/core/trace/index.ts#L208[trace/index.ts:208]
